export type Tara = {
  nume: string;
  codISO: string;
  cotaStandard: number;
  coteReduse?: number[];
  sistem: "flat" | "progresiv" | "distributie" | "cotă-standard" | "cote-multiple" | "proporțional";
  detalii?: string;
  esteRomania?: boolean;
  zona?: "europa" | "extra-europa";
};

export type TipComparatie = {
  id: string;
  titlu: string;
  descriere: string;
  unitateMasura: string;
  culoare: string;
  culoareSecundara: string;
  emoji: string;
  tari: Tara[];
  contextRomania: string;
  mediuEuropean: number;
  istorie: string;
  fapteInteresante: string[];
};

export const COMPARATII: Record<string, TipComparatie> = {
  tva: {
    id: "tva",
    titlu: "TVA — Taxa pe Valoare Adăugată",
    descriere:
      "Comparație internațională a cotelor standard de TVA. România aplică 21% din ianuarie 2026 — la media europeană.",
    unitateMasura: "%",
    culoare: "rgba(37, 99, 235, 0.85)",
    culoareSecundara: "rgba(37, 99, 235, 0.18)",
    emoji: "🛒",
    tari: [
      { nume: "Ungaria", codISO: "HU", cotaStandard: 27, coteReduse: [5, 18], sistem: "cote-multiple" },
      { nume: "Danemarca", codISO: "DK", cotaStandard: 25, coteReduse: [], sistem: "cotă-standard" },
      { nume: "Suedia", codISO: "SE", cotaStandard: 25, coteReduse: [6, 12], sistem: "cote-multiple" },
      { nume: "Norvegia", codISO: "NO", cotaStandard: 25, coteReduse: [12, 15], sistem: "cote-multiple" },
      { nume: "Croația", codISO: "HR", cotaStandard: 25, coteReduse: [5, 13], sistem: "cote-multiple" },
      { nume: "Finlanda", codISO: "FI", cotaStandard: 25.5, coteReduse: [10, 14], sistem: "cote-multiple" },
      { nume: "Polonia", codISO: "PL", cotaStandard: 23, coteReduse: [5, 8], sistem: "cote-multiple" },
      { nume: "Portugalia", codISO: "PT", cotaStandard: 23, coteReduse: [6, 13], sistem: "cote-multiple" },
      { nume: "Irlanda", codISO: "IE", cotaStandard: 23, coteReduse: [9, 13.5], sistem: "cote-multiple" },
      { nume: "Slovacia", codISO: "SK", cotaStandard: 23, coteReduse: [10], sistem: "cote-multiple", detalii: "Ridicată de la 20% în 2025" },
      { nume: "Grecia", codISO: "GR", cotaStandard: 24, coteReduse: [6, 13], sistem: "cote-multiple" },
      { nume: "Islanda", codISO: "IS", cotaStandard: 24, coteReduse: [11], sistem: "cote-multiple" },
      { nume: "Belgia", codISO: "BE", cotaStandard: 21, coteReduse: [6, 12], sistem: "cote-multiple" },
      { nume: "Olanda", codISO: "NL", cotaStandard: 21, coteReduse: [9], sistem: "cote-multiple" },
      { nume: "Cehia", codISO: "CZ", cotaStandard: 21, coteReduse: [12], sistem: "cote-multiple" },
      { nume: "Letonia", codISO: "LV", cotaStandard: 21, coteReduse: [5, 12], sistem: "cote-multiple" },
      { nume: "Lituania", codISO: "LT", cotaStandard: 21, coteReduse: [5, 9], sistem: "cote-multiple" },
      { nume: "Spania", codISO: "ES", cotaStandard: 21, coteReduse: [4, 10], sistem: "cote-multiple" },
      { nume: "Muntenegru", codISO: "ME", cotaStandard: 21, coteReduse: [7], sistem: "cote-multiple" },
      { nume: "Austria", codISO: "AT", cotaStandard: 20, coteReduse: [5, 10, 13], sistem: "cote-multiple" },
      { nume: "Franța", codISO: "FR", cotaStandard: 20, coteReduse: [2.1, 5.5, 10], sistem: "cote-multiple" },
      { nume: "Bulgaria", codISO: "BG", cotaStandard: 20, coteReduse: [9], sistem: "cote-multiple" },
      { nume: "UK", codISO: "GB", cotaStandard: 20, coteReduse: [5], sistem: "cote-multiple", detalii: "0% pentru alimente, cărți" },
      { nume: "Albania", codISO: "AL", cotaStandard: 20, coteReduse: [6], sistem: "cote-multiple" },
      { nume: "Serbia", codISO: "RS", cotaStandard: 20, coteReduse: [10], sistem: "cote-multiple" },
      { nume: "Moldova", codISO: "MD", cotaStandard: 20, coteReduse: [8, 12], sistem: "cote-multiple" },
      { nume: "Ucraina", codISO: "UA", cotaStandard: 20, coteReduse: [7], sistem: "cote-multiple" },
      { nume: "Belarus", codISO: "BY", cotaStandard: 20, coteReduse: [10], sistem: "cote-multiple" },
      { nume: "Armenia", codISO: "AM", cotaStandard: 20, coteReduse: [], sistem: "cotă-standard" },
      { nume: "Turcia", codISO: "TR", cotaStandard: 20, coteReduse: [1, 10], sistem: "cote-multiple" },
      { nume: "Monaco", codISO: "MC", cotaStandard: 20, coteReduse: [2.1, 5.5, 10], sistem: "cote-multiple", detalii: "Aplică sistemul TVA francez" },
      { nume: "Estonia", codISO: "EE", cotaStandard: 22, coteReduse: [9], sistem: "cote-multiple" },
      { nume: "Slovenia", codISO: "SI", cotaStandard: 22, coteReduse: [5, 9.5], sistem: "cote-multiple" },
      { nume: "Italia", codISO: "IT", cotaStandard: 22, coteReduse: [4, 5, 10], sistem: "cote-multiple" },
      { nume: "România", codISO: "RO", cotaStandard: 21, coteReduse: [5, 9], sistem: "cote-multiple", esteRomania: true, detalii: "Majorat de la 19% în ian. 2026" },
      { nume: "Germania", codISO: "DE", cotaStandard: 19, coteReduse: [7], sistem: "cote-multiple" },
      { nume: "Cipru", codISO: "CY", cotaStandard: 19, coteReduse: [5, 9], sistem: "cote-multiple" },
      { nume: "Georgia", codISO: "GE", cotaStandard: 18, coteReduse: [], sistem: "cotă-standard" },
      { nume: "Azerbaijan", codISO: "AZ", cotaStandard: 18, coteReduse: [], sistem: "cotă-standard" },
      { nume: "Macedonia de Nord", codISO: "MK", cotaStandard: 18, coteReduse: [5], sistem: "cote-multiple" },
      { nume: "Kosovo", codISO: "XK", cotaStandard: 18, coteReduse: [8], sistem: "cote-multiple" },
      { nume: "Malta", codISO: "MT", cotaStandard: 18, coteReduse: [5, 7], sistem: "cote-multiple" },
      { nume: "Bosnia-Herțegovina", codISO: "BA", cotaStandard: 17, coteReduse: [], sistem: "cotă-standard" },
      { nume: "Luxemburg", codISO: "LU", cotaStandard: 17, coteReduse: [3, 8, 14], sistem: "cote-multiple" },
      { nume: "Elveția", codISO: "CH", cotaStandard: 8.1, coteReduse: [2.6, 3.8], sistem: "cote-multiple" },
      { nume: "Liechtenstein", codISO: "LI", cotaStandard: 8.1, coteReduse: [2.6, 3.8], sistem: "cote-multiple", detalii: "Aplică sistemul TVA elvețian" },
      { nume: "Andorra", codISO: "AD", cotaStandard: 4.5, coteReduse: [0, 1, 2.5], sistem: "cote-multiple", detalii: "IGI — impozit general indirect" },
      // --- EXTRA-EUROPA ---
      { nume: "Canada", codISO: "CA", cotaStandard: 5, sistem: "cotă-standard", detalii: "5% GST federal + taxe provinciale", zona: "extra-europa" },
      { nume: "Statele Unite", codISO: "US", cotaStandard: 0, sistem: "flat", detalii: "Fără TVA federal — taxe de stat variabile", zona: "extra-europa" },
      { nume: "Mexic", codISO: "MX", cotaStandard: 16, sistem: "flat", zona: "extra-europa" },
      { nume: "Guatemala", codISO: "GT", cotaStandard: 12, sistem: "flat", zona: "extra-europa" },
      { nume: "Belize", codISO: "BZ", cotaStandard: 12.5, sistem: "flat", zona: "extra-europa" },
      { nume: "El Salvador", codISO: "SV", cotaStandard: 13, sistem: "flat", zona: "extra-europa" },
      { nume: "Honduras", codISO: "HN", cotaStandard: 15, sistem: "flat", zona: "extra-europa" },
      { nume: "Nicaragua", codISO: "NI", cotaStandard: 15, sistem: "flat", zona: "extra-europa" },
      { nume: "Costa Rica", codISO: "CR", cotaStandard: 13, sistem: "flat", zona: "extra-europa" },
      { nume: "Panama", codISO: "PA", cotaStandard: 7, sistem: "flat", zona: "extra-europa" },
      { nume: "Cuba", codISO: "CU", cotaStandard: 0, sistem: "flat", detalii: "Fără TVA sistem standard", zona: "extra-europa" },
      { nume: "Jamaica", codISO: "JM", cotaStandard: 15, sistem: "flat", detalii: "GCT 15%", zona: "extra-europa" },
      { nume: "Haiti", codISO: "HT", cotaStandard: 10, sistem: "flat", zona: "extra-europa" },
      { nume: "Republica Dominicană", codISO: "DO", cotaStandard: 18, sistem: "flat", zona: "extra-europa" },
      { nume: "Trinidad și Tobago", codISO: "TT", cotaStandard: 12.5, sistem: "flat", zona: "extra-europa" },
      { nume: "Bahamas", codISO: "BS", cotaStandard: 10, sistem: "flat", zona: "extra-europa" },
      { nume: "Barbados", codISO: "BB", cotaStandard: 17.5, sistem: "flat", zona: "extra-europa" },
      { nume: "Antigua și Barbuda", codISO: "AG", cotaStandard: 15, sistem: "flat", zona: "extra-europa" },
      { nume: "Saint Kitts și Nevis", codISO: "KN", cotaStandard: 17, sistem: "flat", zona: "extra-europa" },
      { nume: "Saint Lucia", codISO: "LC", cotaStandard: 12.5, sistem: "flat", zona: "extra-europa" },
      { nume: "Saint Vincent și Grenadine", codISO: "VC", cotaStandard: 15.5, sistem: "flat", zona: "extra-europa" },
      { nume: "Grenada", codISO: "GD", cotaStandard: 15, sistem: "flat", zona: "extra-europa" },
      { nume: "Dominica", codISO: "DM", cotaStandard: 15, sistem: "flat", zona: "extra-europa" },
      { nume: "Guyana", codISO: "GY", cotaStandard: 14, sistem: "flat", zona: "extra-europa" },
      { nume: "Surinam", codISO: "SR", cotaStandard: 10, sistem: "flat", zona: "extra-europa" },
      { nume: "Columbia", codISO: "CO", cotaStandard: 19, sistem: "flat", zona: "extra-europa" },
      { nume: "Venezuela", codISO: "VE", cotaStandard: 16, sistem: "flat", zona: "extra-europa" },
      { nume: "Ecuador", codISO: "EC", cotaStandard: 12, sistem: "flat", zona: "extra-europa" },
      { nume: "Peru", codISO: "PE", cotaStandard: 18, sistem: "flat", zona: "extra-europa" },
      { nume: "Bolivia", codISO: "BO", cotaStandard: 13, sistem: "flat", zona: "extra-europa" },
      { nume: "Chile", codISO: "CL", cotaStandard: 19, sistem: "flat", zona: "extra-europa" },
      { nume: "Argentina", codISO: "AR", cotaStandard: 21, sistem: "flat", zona: "extra-europa" },
      { nume: "Paraguay", codISO: "PY", cotaStandard: 10, sistem: "flat", zona: "extra-europa" },
      { nume: "Uruguay", codISO: "UY", cotaStandard: 22, sistem: "flat", zona: "extra-europa" },
      { nume: "Brazilia", codISO: "BR", cotaStandard: 12, sistem: "flat", detalii: "IPI+ICMS+ISS ~12% standard federal", zona: "extra-europa" },
      { nume: "Kazahstan", codISO: "KZ", cotaStandard: 12, sistem: "flat", zona: "extra-europa" },
      { nume: "Uzbekistan", codISO: "UZ", cotaStandard: 12, sistem: "flat", zona: "extra-europa" },
      { nume: "Kârgâzstan", codISO: "KG", cotaStandard: 12, sistem: "flat", zona: "extra-europa" },
      { nume: "Tadjikistan", codISO: "TJ", cotaStandard: 18, sistem: "flat", zona: "extra-europa" },
      { nume: "Turkmenistan", codISO: "TM", cotaStandard: 15, sistem: "flat", zona: "extra-europa" },
      { nume: "Mongolia", codISO: "MN", cotaStandard: 10, sistem: "flat", zona: "extra-europa" },
      { nume: "Afghanistan", codISO: "AF", cotaStandard: 10, sistem: "flat", zona: "extra-europa" },
      { nume: "China", codISO: "CN", cotaStandard: 13, sistem: "cote-multiple", detalii: "Cotă standard 13%, redusă 9%/6%", zona: "extra-europa" },
      { nume: "Japonia", codISO: "JP", cotaStandard: 10, sistem: "cote-multiple", detalii: "Standard 10%, redusă 8%", zona: "extra-europa" },
      { nume: "Coreea de Sud", codISO: "KR", cotaStandard: 10, sistem: "flat", zona: "extra-europa" },
      { nume: "Taiwan", codISO: "TW", cotaStandard: 5, sistem: "flat", zona: "extra-europa" },
      { nume: "Hong Kong", codISO: "HK", cotaStandard: 0, sistem: "flat", detalii: "Fără TVA", zona: "extra-europa" },
      { nume: "Macao", codISO: "MO", cotaStandard: 0, sistem: "flat", detalii: "Fără TVA", zona: "extra-europa" },
      { nume: "India", codISO: "IN", cotaStandard: 18, sistem: "cote-multiple", detalii: "GST: 0%/5%/12%/18%/28%", zona: "extra-europa" },
      { nume: "Pakistan", codISO: "PK", cotaStandard: 18, sistem: "cote-multiple", detalii: "Standard 18%, redusă 10%", zona: "extra-europa" },
      { nume: "Bangladesh", codISO: "BD", cotaStandard: 15, sistem: "flat", zona: "extra-europa" },
      { nume: "Sri Lanka", codISO: "LK", cotaStandard: 18, sistem: "flat", zona: "extra-europa" },
      { nume: "Nepal", codISO: "NP", cotaStandard: 13, sistem: "flat", zona: "extra-europa" },
      { nume: "Bhutan", codISO: "BT", cotaStandard: 7, sistem: "flat", zona: "extra-europa" },
      { nume: "Maldive", codISO: "MV", cotaStandard: 16, sistem: "flat", zona: "extra-europa" },
      { nume: "Vietnam", codISO: "VN", cotaStandard: 10, sistem: "cote-multiple", detalii: "Standard 10%, redusă 5%", zona: "extra-europa" },
      { nume: "Thailanda", codISO: "TH", cotaStandard: 7, sistem: "flat", detalii: "Temporar redusă de la 10%", zona: "extra-europa" },
      { nume: "Filipine", codISO: "PH", cotaStandard: 12, sistem: "flat", zona: "extra-europa" },
      { nume: "Indonesia", codISO: "ID", cotaStandard: 11, sistem: "flat", detalii: "Majorată de la 10% în 2022", zona: "extra-europa" },
      { nume: "Malaysia", codISO: "MY", cotaStandard: 6, sistem: "flat", detalii: "SST — Sales and Services Tax", zona: "extra-europa" },
      { nume: "Singapore", codISO: "SG", cotaStandard: 9, sistem: "flat", detalii: "Majorat de la 8% în 2024", zona: "extra-europa" },
      { nume: "Myanmar", codISO: "MM", cotaStandard: 5, sistem: "flat", zona: "extra-europa" },
      { nume: "Cambodgia", codISO: "KH", cotaStandard: 10, sistem: "flat", zona: "extra-europa" },
      { nume: "Laos", codISO: "LA", cotaStandard: 10, sistem: "flat", zona: "extra-europa" },
      { nume: "Brunei", codISO: "BN", cotaStandard: 0, sistem: "flat", detalii: "Fără TVA", zona: "extra-europa" },
      { nume: "Timor-Leste", codISO: "TL", cotaStandard: 0, sistem: "flat", detalii: "Fără TVA standard", zona: "extra-europa" },
      { nume: "Israel", codISO: "IL", cotaStandard: 17, sistem: "flat", zona: "extra-europa" },
      { nume: "Iordania", codISO: "JO", cotaStandard: 16, sistem: "flat", zona: "extra-europa" },
      { nume: "Liban", codISO: "LB", cotaStandard: 11, sistem: "flat", zona: "extra-europa" },
      { nume: "Siria", codISO: "SY", cotaStandard: 11, sistem: "flat", zona: "extra-europa" },
      { nume: "Irak", codISO: "IQ", cotaStandard: 0, sistem: "flat", detalii: "Fără TVA național", zona: "extra-europa" },
      { nume: "Iran", codISO: "IR", cotaStandard: 10, sistem: "flat", zona: "extra-europa" },
      { nume: "Arabia Saudită", codISO: "SA", cotaStandard: 15, sistem: "flat", detalii: "Majorat de la 5% în 2020", zona: "extra-europa" },
      { nume: "Emiratele Arabe Unite", codISO: "AE", cotaStandard: 5, sistem: "flat", detalii: "Introdus în 2018", zona: "extra-europa" },
      { nume: "Qatar", codISO: "QA", cotaStandard: 0, sistem: "flat", detalii: "Fără TVA", zona: "extra-europa" },
      { nume: "Kuwait", codISO: "KW", cotaStandard: 0, sistem: "flat", detalii: "Fără TVA", zona: "extra-europa" },
      { nume: "Bahrain", codISO: "BH", cotaStandard: 10, sistem: "flat", zona: "extra-europa" },
      { nume: "Oman", codISO: "OM", cotaStandard: 5, sistem: "flat", zona: "extra-europa" },
      { nume: "Yemen", codISO: "YE", cotaStandard: 5, sistem: "flat", zona: "extra-europa" },
      { nume: "Maroc", codISO: "MA", cotaStandard: 20, sistem: "cote-multiple", detalii: "Standard 20%, redusă 7%/10%/14%", zona: "extra-europa" },
      { nume: "Algeria", codISO: "DZ", cotaStandard: 19, sistem: "flat", zona: "extra-europa" },
      { nume: "Tunisia", codISO: "TN", cotaStandard: 19, sistem: "cote-multiple", detalii: "19% / 13% / 7%", zona: "extra-europa" },
      { nume: "Egipt", codISO: "EG", cotaStandard: 14, sistem: "flat", zona: "extra-europa" },
      { nume: "Libia", codISO: "LY", cotaStandard: 0, sistem: "flat", detalii: "Fără TVA", zona: "extra-europa" },
      { nume: "Sudan", codISO: "SD", cotaStandard: 17, sistem: "flat", zona: "extra-europa" },
      { nume: "Nigeria", codISO: "NG", cotaStandard: 7.5, sistem: "flat", zona: "extra-europa" },
      { nume: "Kenya", codISO: "KE", cotaStandard: 16, sistem: "flat", zona: "extra-europa" },
      { nume: "Etiopia", codISO: "ET", cotaStandard: 15, sistem: "flat", zona: "extra-europa" },
      { nume: "Tanzania", codISO: "TZ", cotaStandard: 18, sistem: "flat", zona: "extra-europa" },
      { nume: "Uganda", codISO: "UG", cotaStandard: 18, sistem: "flat", zona: "extra-europa" },
      { nume: "Rwanda", codISO: "RW", cotaStandard: 18, sistem: "flat", zona: "extra-europa" },
      { nume: "Ghana", codISO: "GH", cotaStandard: 12.5, sistem: "flat", zona: "extra-europa" },
      { nume: "Camerun", codISO: "CM", cotaStandard: 19.25, sistem: "flat", zona: "extra-europa" },
      { nume: "Senegal", codISO: "SN", cotaStandard: 18, sistem: "flat", zona: "extra-europa" },
      { nume: "Côte d'Ivoire", codISO: "CI", cotaStandard: 18, sistem: "flat", zona: "extra-europa" },
      { nume: "Angola", codISO: "AO", cotaStandard: 14, sistem: "flat", zona: "extra-europa" },
      { nume: "Mozambic", codISO: "MZ", cotaStandard: 17, sistem: "flat", zona: "extra-europa" },
      { nume: "Zambia", codISO: "ZM", cotaStandard: 16, sistem: "flat", zona: "extra-europa" },
      { nume: "Zimbabwe", codISO: "ZW", cotaStandard: 15, sistem: "flat", zona: "extra-europa" },
      { nume: "Malawi", codISO: "MW", cotaStandard: 16.5, sistem: "flat", zona: "extra-europa" },
      { nume: "Namibia", codISO: "NA", cotaStandard: 15, sistem: "flat", zona: "extra-europa" },
      { nume: "Botswana", codISO: "BW", cotaStandard: 12, sistem: "flat", zona: "extra-europa" },
      { nume: "Africa de Sud", codISO: "ZA", cotaStandard: 15, sistem: "flat", zona: "extra-europa" },
      { nume: "Rep. Democrată Congo", codISO: "CD", cotaStandard: 16, sistem: "flat", zona: "extra-europa" },
      { nume: "Congo (Rep.)", codISO: "CG", cotaStandard: 18, sistem: "flat", zona: "extra-europa" },
      { nume: "Madagascar", codISO: "MG", cotaStandard: 20, sistem: "flat", zona: "extra-europa" },
      { nume: "Mali", codISO: "ML", cotaStandard: 18, sistem: "flat", zona: "extra-europa" },
      { nume: "Burkina Faso", codISO: "BF", cotaStandard: 18, sistem: "flat", zona: "extra-europa" },
      { nume: "Niger", codISO: "NE", cotaStandard: 19, sistem: "flat", zona: "extra-europa" },
      { nume: "Togo", codISO: "TG", cotaStandard: 18, sistem: "flat", zona: "extra-europa" },
      { nume: "Benin", codISO: "BJ", cotaStandard: 18, sistem: "flat", zona: "extra-europa" },
      { nume: "Guineea", codISO: "GN", cotaStandard: 18, sistem: "flat", zona: "extra-europa" },
      { nume: "Sierra Leone", codISO: "SL", cotaStandard: 15, sistem: "flat", zona: "extra-europa" },
      { nume: "Liberia", codISO: "LR", cotaStandard: 10, sistem: "flat", zona: "extra-europa" },
      { nume: "Gambia", codISO: "GM", cotaStandard: 15, sistem: "flat", zona: "extra-europa" },
      { nume: "Guineea-Bissau", codISO: "GW", cotaStandard: 17, sistem: "flat", zona: "extra-europa" },
      { nume: "Mauritania", codISO: "MR", cotaStandard: 16, sistem: "flat", zona: "extra-europa" },
      { nume: "Capul Verde", codISO: "CV", cotaStandard: 15, sistem: "flat", zona: "extra-europa" },
      { nume: "Guineea Ecuatorială", codISO: "GQ", cotaStandard: 15, sistem: "flat", zona: "extra-europa" },
      { nume: "Gabon", codISO: "GA", cotaStandard: 18, sistem: "flat", zona: "extra-europa" },
      { nume: "Rep. Centrafricană", codISO: "CF", cotaStandard: 19, sistem: "flat", zona: "extra-europa" },
      { nume: "Ciad", codISO: "TD", cotaStandard: 18, sistem: "flat", zona: "extra-europa" },
      { nume: "Sudan de Sud", codISO: "SS", cotaStandard: 18, sistem: "flat", zona: "extra-europa" },
      { nume: "Somalia", codISO: "SO", cotaStandard: 0, sistem: "flat", detalii: "Fără TVA funcțional", zona: "extra-europa" },
      { nume: "Djibouti", codISO: "DJ", cotaStandard: 0, sistem: "flat", detalii: "Fără TVA", zona: "extra-europa" },
      { nume: "Eritreea", codISO: "ER", cotaStandard: 5, sistem: "flat", zona: "extra-europa" },
      { nume: "Burundi", codISO: "BI", cotaStandard: 18, sistem: "flat", zona: "extra-europa" },
      { nume: "Comore", codISO: "KM", cotaStandard: 10, sistem: "flat", zona: "extra-europa" },
      { nume: "Mauritius", codISO: "MU", cotaStandard: 15, sistem: "flat", zona: "extra-europa" },
      { nume: "Seychelles", codISO: "SC", cotaStandard: 15, sistem: "flat", zona: "extra-europa" },
      { nume: "Eswatini", codISO: "SZ", cotaStandard: 15, sistem: "flat", zona: "extra-europa" },
      { nume: "Lesotho", codISO: "LS", cotaStandard: 15, sistem: "flat", zona: "extra-europa" },
      { nume: "São Tomé și Príncipe", codISO: "ST", cotaStandard: 0, sistem: "flat", detalii: "Fără TVA", zona: "extra-europa" },
      { nume: "Australia", codISO: "AU", cotaStandard: 10, sistem: "flat", detalii: "GST 10%", zona: "extra-europa" },
      { nume: "Noua Zeelandă", codISO: "NZ", cotaStandard: 15, sistem: "flat", zona: "extra-europa" },
      { nume: "Papua Noua Guinee", codISO: "PG", cotaStandard: 10, sistem: "flat", zona: "extra-europa" },
      { nume: "Fiji", codISO: "FJ", cotaStandard: 9, sistem: "flat", zona: "extra-europa" },
      { nume: "Samoa", codISO: "WS", cotaStandard: 15, sistem: "flat", zona: "extra-europa" },
      { nume: "Tonga", codISO: "TO", cotaStandard: 15, sistem: "flat", zona: "extra-europa" },
      { nume: "Vanuatu", codISO: "VU", cotaStandard: 15, sistem: "flat", zona: "extra-europa" },
      { nume: "Insulele Solomon", codISO: "SB", cotaStandard: 10, sistem: "flat", zona: "extra-europa" },
      { nume: "Kiribati", codISO: "KI", cotaStandard: 0, sistem: "flat", detalii: "Fără TVA", zona: "extra-europa" },
      { nume: "Micronezia", codISO: "FM", cotaStandard: 0, sistem: "flat", detalii: "Fără TVA", zona: "extra-europa" },
      { nume: "Palau", codISO: "PW", cotaStandard: 0, sistem: "flat", detalii: "Fără TVA", zona: "extra-europa" },
      { nume: "Insulele Marshall", codISO: "MH", cotaStandard: 0, sistem: "flat", detalii: "Fără TVA", zona: "extra-europa" },
      { nume: "Tuvalu", codISO: "TV", cotaStandard: 0, sistem: "flat", detalii: "Fără TVA", zona: "extra-europa" },
      { nume: "Nauru", codISO: "NR", cotaStandard: 0, sistem: "flat", detalii: "Fără TVA", zona: "extra-europa" },
    ],
    contextRomania:
      "România a majorat TVA de la 19% la 21% începând cu 1 ianuarie 2026, în contextul consolidării fiscale. Se situează acum la media UE (~21%). Cota redusă de 9% se aplică pentru alimente, medicamente și servicii de turism, iar 5% pentru locuințe sociale și produse ecologice. TVA la încasare rămâne disponibilă pentru contribuabilii sub 4.500.000 lei.",
    mediuEuropean: 21,
    istorie:
      "TVA a fost inventată în Franța în 1954 de către Maurice Lauré, director adjunct al administrației fiscale franceze. Ideea revoluționară a fost că fiecare verigă din lanțul de producție și distribuție plătește impozit doar pe valoarea adăugată de ea, nu pe valoarea totală a tranzacției. România a introdus TVA în 1993, la scurt timp după tranziția la economia de piață, cu o cotă inițială de 18%. Cota a crescut la 19% în 1998, a urcat la 24% în 2010 (în contextul crizei economice și al acordului cu FMI), a scăzut la 20% în 2016 și la 19% în 2017, apoi a crescut din nou la 21% în ianuarie 2026 ca parte din măsurile de consolidare fiscală. Uniunea Europeană impune statelor membre o cotă minimă de TVA de 15%, dar fiecare stat are libertatea să stabilească propria cotă standard.",
    fapteInteresante: [
      "Ungaria are cea mai mare cotă de TVA din lume — 27% — mai mare decât orice altă țară OCDE.",
      "Luxemburg, deși are cea mai mică cotă din UE (17%), găzduiește sediile multor companii tech datorită avantajelor fiscale.",
      "Elveția și Liechtenstein aplică una dintre cele mai mici cote TVA europene: 8.1%, cu cote reduse de 2.6% pentru alimente de bază.",
      "Andorra are cea mai mică cotă TVA din Europa (4.5%) și nu este membră UE, atras mult turism de cumpărături.",
      "Bosnia-Herțegovina (17%) are un singur nivel TVA fără cote reduse — sistem simplu dar inflexibil.",
    ],
  },

  "impozit-venit": {
    id: "impozit-venit",
    titlu: "Impozit pe Venit — Persoane Fizice",
    descriere:
      "Comparație a sistemelor de impozitare a veniturilor persoanelor fizice în Europa. România aplică o cotă unică de 10%.",
    unitateMasura: "%",
    culoare: "rgba(5, 150, 105, 0.85)",
    culoareSecundara: "rgba(5, 150, 105, 0.18)",
    emoji: "💼",
    tari: [
      { nume: "Danemarca", codISO: "DK", cotaStandard: 56, sistem: "progresiv", detalii: "Cotă marginală maximă" },
      { nume: "Austria", codISO: "AT", cotaStandard: 55, sistem: "progresiv", detalii: "Cotă marginală maximă" },
      { nume: "Suedia", codISO: "SE", cotaStandard: 52, sistem: "progresiv", detalii: "Cotă marginală maximă" },
      { nume: "Slovenia", codISO: "SI", cotaStandard: 50, sistem: "progresiv", detalii: "Cotă marginală maximă" },
      { nume: "Olanda", codISO: "NL", cotaStandard: 49.5, sistem: "progresiv", detalii: "Cotă marginală maximă" },
      { nume: "Norvegia", codISO: "NO", cotaStandard: 47.4, sistem: "progresiv", detalii: "Cotă marginală maximă incl. supertaxă" },
      { nume: "Islanda", codISO: "IS", cotaStandard: 46.3, sistem: "progresiv", detalii: "Cotă marginală maximă" },
      { nume: "Belgia", codISO: "BE", cotaStandard: 50, sistem: "progresiv", detalii: "Cotă marginală maximă" },
      { nume: "Finlanda", codISO: "FI", cotaStandard: 51.4, sistem: "progresiv", detalii: "Cotă marginală maximă" },
      { nume: "Portugalia", codISO: "PT", cotaStandard: 48, sistem: "progresiv", detalii: "Cotă marginală maximă" },
      { nume: "Spania", codISO: "ES", cotaStandard: 47, sistem: "progresiv", detalii: "Cotă marginală maximă" },
      { nume: "Franța", codISO: "FR", cotaStandard: 45, sistem: "progresiv", detalii: "Cotă marginală maximă" },
      { nume: "Germania", codISO: "DE", cotaStandard: 45, sistem: "progresiv", detalii: "Cotă marginală maximă" },
      { nume: "UK", codISO: "GB", cotaStandard: 45, sistem: "progresiv", detalii: "Cotă marginală maximă" },
      { nume: "Grecia", codISO: "GR", cotaStandard: 44, sistem: "progresiv", detalii: "Cotă marginală maximă" },
      { nume: "Italia", codISO: "IT", cotaStandard: 43, sistem: "progresiv", detalii: "Cotă marginală maximă" },
      { nume: "Luxemburg", codISO: "LU", cotaStandard: 42, sistem: "progresiv", detalii: "Cotă marginală maximă" },
      { nume: "Elveția", codISO: "CH", cotaStandard: 41.5, sistem: "progresiv", detalii: "Federal + cantonal, variabil" },
      { nume: "Turcia", codISO: "TR", cotaStandard: 40, sistem: "progresiv", detalii: "Cotă marginală maximă" },
      { nume: "Irlanda", codISO: "IE", cotaStandard: 40, sistem: "progresiv", detalii: "Cotă marginală maximă" },
      { nume: "Croația", codISO: "HR", cotaStandard: 35.4, sistem: "progresiv", detalii: "Cotă marginală maximă" },
      { nume: "Malta", codISO: "MT", cotaStandard: 35, sistem: "progresiv", detalii: "Cotă marginală maximă" },
      { nume: "Cipru", codISO: "CY", cotaStandard: 35, sistem: "progresiv", detalii: "Cotă marginală maximă" },
      { nume: "San Marino", codISO: "SM", cotaStandard: 35, sistem: "progresiv", detalii: "Cotă marginală maximă" },
      { nume: "Serbia", codISO: "RS", cotaStandard: 20, sistem: "flat", detalii: "Cotă unică 20%" },
      { nume: "Georgia", codISO: "GE", cotaStandard: 20, sistem: "flat", detalii: "Cotă unică 20%" },
      { nume: "Ucraina", codISO: "UA", cotaStandard: 18, sistem: "flat", detalii: "Cotă unică 18%" },
      { nume: "Liechtenstein", codISO: "LI", cotaStandard: 17.82, sistem: "flat", detalii: "Cotă maximă efectivă ~17.82%" },
      { nume: "Ungaria", codISO: "HU", cotaStandard: 15, sistem: "flat", detalii: "Cotă unică 15%" },
      { nume: "Muntenegru", codISO: "ME", cotaStandard: 15, sistem: "progresiv", detalii: "9% / 15%" },
      { nume: "Albania", codISO: "AL", cotaStandard: 23, sistem: "progresiv", detalii: "0% / 13% / 23%" },
      { nume: "Azerbaijan", codISO: "AZ", cotaStandard: 25, sistem: "progresiv", detalii: "14% / 25%" },
      { nume: "Moldova", codISO: "MD", cotaStandard: 12, sistem: "flat", detalii: "Cotă unică 12%" },
      { nume: "Macedonia de Nord", codISO: "MK", cotaStandard: 10, sistem: "flat", detalii: "Cotă unică 10%" },
      { nume: "Kosovo", codISO: "XK", cotaStandard: 10, sistem: "flat", detalii: "Cotă unică 10%" },
      { nume: "Bosnia-Herțegovina", codISO: "BA", cotaStandard: 10, sistem: "flat", detalii: "Cotă unică 10%" },
      { nume: "Belarus", codISO: "BY", cotaStandard: 13, sistem: "flat", detalii: "Cotă unică 13%" },
      { nume: "Armenia", codISO: "AM", cotaStandard: 20, sistem: "flat", detalii: "Cotă unică 20%" },
      { nume: "Andorra", codISO: "AD", cotaStandard: 10, sistem: "progresiv", detalii: "0% / 5% / 10%" },
      { nume: "Monaco", codISO: "MC", cotaStandard: 0, sistem: "flat", detalii: "Fără impozit pe venit personal" },
      { nume: "Letonia", codISO: "LV", cotaStandard: 31, sistem: "progresiv", detalii: "20% / 23% / 31%" },
      { nume: "Lituania", codISO: "LT", cotaStandard: 32, sistem: "progresiv", detalii: "20% / 32%" },
      { nume: "Polonia", codISO: "PL", cotaStandard: 32, sistem: "progresiv", detalii: "12% / 32%" },
      { nume: "Slovacia", codISO: "SK", cotaStandard: 25, sistem: "progresiv", detalii: "19% / 25%" },
      { nume: "Cehia", codISO: "CZ", cotaStandard: 23, sistem: "progresiv", detalii: "15% / 23%" },
      { nume: "Estonia", codISO: "EE", cotaStandard: 22, sistem: "flat", detalii: "Cotă unică 22%" },
      { nume: "Bulgaria", codISO: "BG", cotaStandard: 10, sistem: "flat", detalii: "Cotă unică 10%" },
      {
        nume: "România",
        codISO: "RO",
        cotaStandard: 10,
        sistem: "flat",
        detalii: "Cotă unică 10%",
        esteRomania: true,
      },
      // --- EXTRA-EUROPA ---
      { nume: "Statele Unite", codISO: "US", cotaStandard: 37, sistem: "progresiv", detalii: "Federal: 10%–37%", zona: "extra-europa" },
      { nume: "Canada", codISO: "CA", cotaStandard: 33, sistem: "progresiv", detalii: "Federal: 15%–33%, + provincial", zona: "extra-europa" },
      { nume: "Mexic", codISO: "MX", cotaStandard: 35, sistem: "progresiv", detalii: "ISR: 1.92%–35%", zona: "extra-europa" },
      { nume: "Brazilia", codISO: "BR", cotaStandard: 27.5, sistem: "progresiv", detalii: "0%–27.5%", zona: "extra-europa" },
      { nume: "Argentina", codISO: "AR", cotaStandard: 35, sistem: "progresiv", detalii: "0%–35%", zona: "extra-europa" },
      { nume: "Chile", codISO: "CL", cotaStandard: 40, sistem: "progresiv", detalii: "0%–40%", zona: "extra-europa" },
      { nume: "Columbia", codISO: "CO", cotaStandard: 39, sistem: "progresiv", detalii: "0%–39%", zona: "extra-europa" },
      { nume: "Peru", codISO: "PE", cotaStandard: 30, sistem: "progresiv", detalii: "0%–30%", zona: "extra-europa" },
      { nume: "Venezuela", codISO: "VE", cotaStandard: 34, sistem: "progresiv", detalii: "6%–34%", zona: "extra-europa" },
      { nume: "Uruguay", codISO: "UY", cotaStandard: 36, sistem: "progresiv", detalii: "0%–36%", zona: "extra-europa" },
      { nume: "Ecuador", codISO: "EC", cotaStandard: 37, sistem: "progresiv", detalii: "0%–37%", zona: "extra-europa" },
      { nume: "Bolivia", codISO: "BO", cotaStandard: 13, sistem: "flat", detalii: "RC-IVA 13%", zona: "extra-europa" },
      { nume: "Paraguay", codISO: "PY", cotaStandard: 10, sistem: "flat", detalii: "IRP 10%", zona: "extra-europa" },
      { nume: "Cuba", codISO: "CU", cotaStandard: 50, sistem: "progresiv", detalii: "Cotă maximă 50%", zona: "extra-europa" },
      { nume: "Jamaica", codISO: "JM", cotaStandard: 30, sistem: "progresiv", detalii: "0%–30%", zona: "extra-europa" },
      { nume: "Trinidad și Tobago", codISO: "TT", cotaStandard: 25, sistem: "flat", detalii: "25% standard", zona: "extra-europa" },
      { nume: "Republica Dominicană", codISO: "DO", cotaStandard: 25, sistem: "progresiv", detalii: "0%–25%", zona: "extra-europa" },
      { nume: "Panama", codISO: "PA", cotaStandard: 25, sistem: "progresiv", detalii: "0%–25%", zona: "extra-europa" },
      { nume: "Costa Rica", codISO: "CR", cotaStandard: 25, sistem: "progresiv", detalii: "0%–25%", zona: "extra-europa" },
      { nume: "Guatemala", codISO: "GT", cotaStandard: 7, sistem: "flat", detalii: "ISR 7% pe venituri", zona: "extra-europa" },
      { nume: "El Salvador", codISO: "SV", cotaStandard: 30, sistem: "progresiv", detalii: "0%–30%", zona: "extra-europa" },
      { nume: "Honduras", codISO: "HN", cotaStandard: 25, sistem: "progresiv", detalii: "0%–25%", zona: "extra-europa" },
      { nume: "Nicaragua", codISO: "NI", cotaStandard: 30, sistem: "progresiv", detalii: "0%–30%", zona: "extra-europa" },
      { nume: "China", codISO: "CN", cotaStandard: 45, sistem: "progresiv", detalii: "Federal: 3%–45%", zona: "extra-europa" },
      { nume: "Japonia", codISO: "JP", cotaStandard: 55, sistem: "progresiv", detalii: "Federal 45% + local 10%", zona: "extra-europa" },
      { nume: "Coreea de Sud", codISO: "KR", cotaStandard: 45, sistem: "progresiv", detalii: "6%–45% + 10% local", zona: "extra-europa" },
      { nume: "Taiwan", codISO: "TW", cotaStandard: 40, sistem: "progresiv", detalii: "5%–40%", zona: "extra-europa" },
      { nume: "Hong Kong", codISO: "HK", cotaStandard: 17, sistem: "flat", detalii: "Standard rate 17%", zona: "extra-europa" },
      { nume: "Singapore", codISO: "SG", cotaStandard: 24, sistem: "progresiv", detalii: "0%–24%", zona: "extra-europa" },
      { nume: "Malaysia", codISO: "MY", cotaStandard: 30, sistem: "progresiv", detalii: "0%–30%", zona: "extra-europa" },
      { nume: "Thailanda", codISO: "TH", cotaStandard: 35, sistem: "progresiv", detalii: "5%–35%", zona: "extra-europa" },
      { nume: "Vietnam", codISO: "VN", cotaStandard: 35, sistem: "progresiv", detalii: "5%–35%", zona: "extra-europa" },
      { nume: "Filipine", codISO: "PH", cotaStandard: 35, sistem: "progresiv", detalii: "0%–35%", zona: "extra-europa" },
      { nume: "Indonesia", codISO: "ID", cotaStandard: 35, sistem: "progresiv", detalii: "5%–35%", zona: "extra-europa" },
      { nume: "India", codISO: "IN", cotaStandard: 30, sistem: "progresiv", detalii: "0%–30%", zona: "extra-europa" },
      { nume: "Pakistan", codISO: "PK", cotaStandard: 35, sistem: "progresiv", detalii: "0%–35%", zona: "extra-europa" },
      { nume: "Bangladesh", codISO: "BD", cotaStandard: 30, sistem: "progresiv", detalii: "0%–30%", zona: "extra-europa" },
      { nume: "Sri Lanka", codISO: "LK", cotaStandard: 36, sistem: "progresiv", detalii: "6%–36%", zona: "extra-europa" },
      { nume: "Nepal", codISO: "NP", cotaStandard: 36, sistem: "progresiv", detalii: "0%–36%", zona: "extra-europa" },
      { nume: "Mongolia", codISO: "MN", cotaStandard: 20, sistem: "flat", detalii: "10%–20%", zona: "extra-europa" },
      { nume: "Kazahstan", codISO: "KZ", cotaStandard: 10, sistem: "flat", detalii: "Cotă unică 10%", zona: "extra-europa" },
      { nume: "Uzbekistan", codISO: "UZ", cotaStandard: 12, sistem: "flat", detalii: "Cotă unică 12%", zona: "extra-europa" },
      { nume: "Kârgâzstan", codISO: "KG", cotaStandard: 10, sistem: "flat", detalii: "Cotă unică 10%", zona: "extra-europa" },
      { nume: "Tadjikistan", codISO: "TJ", cotaStandard: 13, sistem: "flat", detalii: "Cotă unică 13%", zona: "extra-europa" },
      { nume: "Arabia Saudită", codISO: "SA", cotaStandard: 0, sistem: "flat", detalii: "Fără impozit pe venit", zona: "extra-europa" },
      { nume: "Emiratele Arabe Unite", codISO: "AE", cotaStandard: 0, sistem: "flat", detalii: "Fără impozit pe venit personal", zona: "extra-europa" },
      { nume: "Qatar", codISO: "QA", cotaStandard: 0, sistem: "flat", detalii: "Fără impozit pe venit", zona: "extra-europa" },
      { nume: "Kuwait", codISO: "KW", cotaStandard: 0, sistem: "flat", detalii: "Fără impozit pe venit", zona: "extra-europa" },
      { nume: "Bahrain", codISO: "BH", cotaStandard: 0, sistem: "flat", detalii: "Fără impozit pe venit", zona: "extra-europa" },
      { nume: "Oman", codISO: "OM", cotaStandard: 0, sistem: "flat", detalii: "Fără impozit pe venit personal", zona: "extra-europa" },
      { nume: "Israel", codISO: "IL", cotaStandard: 50, sistem: "progresiv", detalii: "10%–50%", zona: "extra-europa" },
      { nume: "Iordania", codISO: "JO", cotaStandard: 20, sistem: "progresiv", detalii: "0%–20%", zona: "extra-europa" },
      { nume: "Liban", codISO: "LB", cotaStandard: 25, sistem: "progresiv", detalii: "4%–25%", zona: "extra-europa" },
      { nume: "Irak", codISO: "IQ", cotaStandard: 15, sistem: "flat", detalii: "Cotă maximă 15%", zona: "extra-europa" },
      { nume: "Iran", codISO: "IR", cotaStandard: 35, sistem: "progresiv", detalii: "15%–35%", zona: "extra-europa" },
      { nume: "Egipt", codISO: "EG", cotaStandard: 27.5, sistem: "progresiv", detalii: "0%–27.5%", zona: "extra-europa" },
      { nume: "Maroc", codISO: "MA", cotaStandard: 38, sistem: "progresiv", detalii: "0%–38%", zona: "extra-europa" },
      { nume: "Algeria", codISO: "DZ", cotaStandard: 35, sistem: "progresiv", detalii: "0%–35%", zona: "extra-europa" },
      { nume: "Tunisia", codISO: "TN", cotaStandard: 35, sistem: "progresiv", detalii: "0%–35%", zona: "extra-europa" },
      { nume: "Africa de Sud", codISO: "ZA", cotaStandard: 45, sistem: "progresiv", detalii: "18%–45%", zona: "extra-europa" },
      { nume: "Nigeria", codISO: "NG", cotaStandard: 24, sistem: "progresiv", detalii: "7%–24%", zona: "extra-europa" },
      { nume: "Kenya", codISO: "KE", cotaStandard: 30, sistem: "progresiv", detalii: "10%–30%", zona: "extra-europa" },
      { nume: "Etiopia", codISO: "ET", cotaStandard: 35, sistem: "progresiv", detalii: "0%–35%", zona: "extra-europa" },
      { nume: "Ghana", codISO: "GH", cotaStandard: 35, sistem: "progresiv", detalii: "0%–35%", zona: "extra-europa" },
      { nume: "Tanzania", codISO: "TZ", cotaStandard: 30, sistem: "progresiv", detalii: "0%–30%", zona: "extra-europa" },
      { nume: "Uganda", codISO: "UG", cotaStandard: 40, sistem: "progresiv", detalii: "0%–40%", zona: "extra-europa" },
      { nume: "Australia", codISO: "AU", cotaStandard: 45, sistem: "progresiv", detalii: "0%–45%", zona: "extra-europa" },
      { nume: "Noua Zeelandă", codISO: "NZ", cotaStandard: 39, sistem: "progresiv", detalii: "10.5%–39%", zona: "extra-europa" },
    ],
    contextRomania:
      "România și Bulgaria sunt singurele țări UE cu o cotă unică de impozit pe venit de 10% — cea mai mică din Europa. Această cotă avantajează semnificativ persoanele cu venituri medii și mari față de sistemele progresive din vest. PFA-urile și liber profesioniștii plătesc 10% + CAS 25% + CASS 10% din venitul net anual.",
    mediuEuropean: 38,
    istorie:
      "Impozitul pe venitul personal a apărut pentru prima dată în Marea Britanie în 1799, introdus de William Pitt cel Tânăr pentru a finanța războaiele napoleoniene. Statele Unite au introdus impozitul pe venit prin Amendamentul XVI din 1913. România a adoptat impozitul pe venit odată cu reformele fiscale din anii 1990. Inițial a existat un sistem progresiv cu mai multe trepte (18%, 23%, 28%), dar în 2005 guvernul Călin Popescu-Tăriceanu a introdus cota unică de 16%, considerată un avantaj competitiv pentru atragerea investițiilor. Din 2018, cota a fost redusă la 10% pentru persoanele fizice, concomitent cu transferul contribuțiilor sociale de la angajator la angajat.",
    fapteInteresante: [
      "Bulgaria și România sunt singurele state UE cu cotă unică de 10% — cele mai mici din blocul comunitar.",
      "Monaco nu aplică niciun impozit pe venitul personal — atrage mii de milionari și celebrități ca rezidenți fiscali.",
      "Danemarca are cea mai mare cotă marginală din Europa (56%), dar și cel mai generos sistem de protecție socială.",
      "Estonia a fost prima țară din Europa Centrală și de Est care a introdus cota unică (1994), inspirând alte țări din regiune.",
      "Kosovo, Bosnia și Macedonia de Nord aplică cote unice de 10% — la fel ca România, reflectând modelul fiscal est-european.",
    ],
  },

  "impozit-profit": {
    id: "impozit-profit",
    titlu: "Impozit pe Profit — Persoane Juridice",
    descriere:
      "Comparație a cotelor de impozit pe profit pentru companii în Europa. România aplică 16% (sau 1% microîntreprinderi).",
    unitateMasura: "%",
    culoare: "rgba(124, 58, 237, 0.85)",
    culoareSecundara: "rgba(124, 58, 237, 0.18)",
    emoji: "🏢",
    tari: [
      { nume: "Malta", codISO: "MT", cotaStandard: 35, sistem: "flat", detalii: "Efectiv ~5% cu restituiri" },
      { nume: "Germania", codISO: "DE", cotaStandard: 30, sistem: "flat", detalii: "~30% combinat (federal + local)" },
      { nume: "Turcia", codISO: "TR", cotaStandard: 25, sistem: "flat" },
      { nume: "UK", codISO: "GB", cotaStandard: 25, sistem: "flat", detalii: "19% pentru profituri sub 50k GBP" },
      { nume: "Franța", codISO: "FR", cotaStandard: 25, sistem: "flat", detalii: "Cotă standard 25%" },
      { nume: "Spania", codISO: "ES", cotaStandard: 25, sistem: "flat" },
      { nume: "Belgia", codISO: "BE", cotaStandard: 25, sistem: "flat" },
      { nume: "Olanda", codISO: "NL", cotaStandard: 25.8, sistem: "progresiv", detalii: "19% / 25.8%" },
      { nume: "Grecia", codISO: "GR", cotaStandard: 22, sistem: "flat" },
      { nume: "Danemarca", codISO: "DK", cotaStandard: 22, sistem: "flat" },
      { nume: "Norvegia", codISO: "NO", cotaStandard: 22, sistem: "flat" },
      { nume: "Islanda", codISO: "IS", cotaStandard: 20, sistem: "flat" },
      { nume: "Finlanda", codISO: "FI", cotaStandard: 20, sistem: "flat" },
      { nume: "Estonia", codISO: "EE", cotaStandard: 20, sistem: "distributie", detalii: "Doar pe profitul distribuit" },
      { nume: "Letonia", codISO: "LV", cotaStandard: 20, sistem: "distributie", detalii: "Doar pe profitul distribuit" },
      { nume: "Suedia", codISO: "SE", cotaStandard: 20.6, sistem: "flat" },
      { nume: "Ucraina", codISO: "UA", cotaStandard: 18, sistem: "flat" },
      { nume: "Belarus", codISO: "BY", cotaStandard: 18, sistem: "flat" },
      { nume: "Croația", codISO: "HR", cotaStandard: 18, sistem: "flat", detalii: "10% sub 1M EUR profit" },
      { nume: "Austria", codISO: "AT", cotaStandard: 23, sistem: "flat", detalii: "Redus de la 25% în 2023" },
      { nume: "Italia", codISO: "IT", cotaStandard: 24, sistem: "flat", detalii: "24% IRES + 3.9% IRAP" },
      { nume: "Portugalia", codISO: "PT", cotaStandard: 21, sistem: "flat", detalii: "21% + surtaxe locale" },
      { nume: "Cehia", codISO: "CZ", cotaStandard: 21, sistem: "flat" },
      { nume: "Slovacia", codISO: "SK", cotaStandard: 21, sistem: "flat" },
      { nume: "Azerbaidjan", codISO: "AZ", cotaStandard: 20, sistem: "flat" },
      { nume: "Armenia", codISO: "AM", cotaStandard: 18, sistem: "flat" },
      { nume: "Serbia", codISO: "RS", cotaStandard: 15, sistem: "flat" },
      { nume: "Albania", codISO: "AL", cotaStandard: 15, sistem: "flat" },
      { nume: "Georgia", codISO: "GE", cotaStandard: 15, sistem: "flat", detalii: "0% pe profit reinvestit" },
      { nume: "Lituania", codISO: "LT", cotaStandard: 15, sistem: "flat", detalii: "5% pentru firme mici" },
      { nume: "Moldova", codISO: "MD", cotaStandard: 12, sistem: "flat" },
      { nume: "Cipru", codISO: "CY", cotaStandard: 12.5, sistem: "flat" },
      { nume: "Irlanda", codISO: "IE", cotaStandard: 12.5, sistem: "flat", detalii: "Renumit pentru firme tech" },
      { nume: "Liechtenstein", codISO: "LI", cotaStandard: 12.5, sistem: "flat" },
      { nume: "Elveția", codISO: "CH", cotaStandard: 14.9, sistem: "flat", detalii: "Medie cantoane ~14.9%" },
      { nume: "Kosovo", codISO: "XK", cotaStandard: 10, sistem: "flat" },
      { nume: "Macedonia de Nord", codISO: "MK", cotaStandard: 10, sistem: "flat" },
      { nume: "Bosnia-Herțegovina", codISO: "BA", cotaStandard: 10, sistem: "flat" },
      { nume: "Andorra", codISO: "AD", cotaStandard: 10, sistem: "flat" },
      { nume: "Bulgaria", codISO: "BG", cotaStandard: 10, sistem: "flat" },
      { nume: "Muntenegru", codISO: "ME", cotaStandard: 9, sistem: "flat" },
      { nume: "Ungaria", codISO: "HU", cotaStandard: 9, sistem: "flat", detalii: "Cea mai mică din UE" },
      { nume: "Luxemburg", codISO: "LU", cotaStandard: 17, sistem: "flat" },
      { nume: "Polonia", codISO: "PL", cotaStandard: 19, sistem: "flat", detalii: "9% pentru firme mici" },
      { nume: "Slovenia", codISO: "SI", cotaStandard: 19, sistem: "flat" },
      {
        nume: "România",
        codISO: "RO",
        cotaStandard: 16,
        sistem: "flat",
        detalii: "16% profit / 1% micro",
        esteRomania: true,
      },
      // --- EXTRA-EUROPA ---
      { nume: "Statele Unite", codISO: "US", cotaStandard: 21, sistem: "flat", detalii: "Federal 21% + taxe de stat", zona: "extra-europa" },
      { nume: "Canada", codISO: "CA", cotaStandard: 26.5, sistem: "flat", detalii: "Federal 15% + provincial ~11.5%", zona: "extra-europa" },
      { nume: "Mexic", codISO: "MX", cotaStandard: 30, sistem: "flat", zona: "extra-europa" },
      { nume: "Brazilia", codISO: "BR", cotaStandard: 25, sistem: "flat", detalii: "15% IRPJ + 10% adicional", zona: "extra-europa" },
      { nume: "Argentina", codISO: "AR", cotaStandard: 35, sistem: "flat", zona: "extra-europa" },
      { nume: "Chile", codISO: "CL", cotaStandard: 27, sistem: "flat", zona: "extra-europa" },
      { nume: "Columbia", codISO: "CO", cotaStandard: 35, sistem: "flat", zona: "extra-europa" },
      { nume: "Peru", codISO: "PE", cotaStandard: 29.5, sistem: "flat", zona: "extra-europa" },
      { nume: "Venezuela", codISO: "VE", cotaStandard: 34, sistem: "flat", zona: "extra-europa" },
      { nume: "Uruguay", codISO: "UY", cotaStandard: 25, sistem: "flat", zona: "extra-europa" },
      { nume: "Ecuador", codISO: "EC", cotaStandard: 25, sistem: "flat", zona: "extra-europa" },
      { nume: "Bolivia", codISO: "BO", cotaStandard: 25, sistem: "flat", zona: "extra-europa" },
      { nume: "Paraguay", codISO: "PY", cotaStandard: 10, sistem: "flat", zona: "extra-europa" },
      { nume: "Panama", codISO: "PA", cotaStandard: 25, sistem: "flat", zona: "extra-europa" },
      { nume: "Costa Rica", codISO: "CR", cotaStandard: 30, sistem: "flat", zona: "extra-europa" },
      { nume: "Jamaica", codISO: "JM", cotaStandard: 25, sistem: "flat", zona: "extra-europa" },
      { nume: "China", codISO: "CN", cotaStandard: 25, sistem: "flat", detalii: "25% standard (15% pentru tehnologie)", zona: "extra-europa" },
      { nume: "Japonia", codISO: "JP", cotaStandard: 23.2, sistem: "flat", detalii: "Federal 23.2%, total efectiv ~30%", zona: "extra-europa" },
      { nume: "Coreea de Sud", codISO: "KR", cotaStandard: 24, sistem: "progresiv", detalii: "9%–24%", zona: "extra-europa" },
      { nume: "Taiwan", codISO: "TW", cotaStandard: 20, sistem: "flat", zona: "extra-europa" },
      { nume: "Hong Kong", codISO: "HK", cotaStandard: 16.5, sistem: "flat", zona: "extra-europa" },
      { nume: "Singapore", codISO: "SG", cotaStandard: 17, sistem: "flat", zona: "extra-europa" },
      { nume: "Malaysia", codISO: "MY", cotaStandard: 24, sistem: "flat", zona: "extra-europa" },
      { nume: "Thailanda", codISO: "TH", cotaStandard: 20, sistem: "flat", zona: "extra-europa" },
      { nume: "Vietnam", codISO: "VN", cotaStandard: 20, sistem: "flat", zona: "extra-europa" },
      { nume: "Filipine", codISO: "PH", cotaStandard: 25, sistem: "flat", zona: "extra-europa" },
      { nume: "Indonesia", codISO: "ID", cotaStandard: 22, sistem: "flat", zona: "extra-europa" },
      { nume: "India", codISO: "IN", cotaStandard: 25.17, sistem: "flat", detalii: "22% + suprataxa", zona: "extra-europa" },
      { nume: "Pakistan", codISO: "PK", cotaStandard: 29, sistem: "flat", zona: "extra-europa" },
      { nume: "Bangladesh", codISO: "BD", cotaStandard: 27.5, sistem: "flat", zona: "extra-europa" },
      { nume: "Sri Lanka", codISO: "LK", cotaStandard: 30, sistem: "flat", zona: "extra-europa" },
      { nume: "Kazahstan", codISO: "KZ", cotaStandard: 20, sistem: "flat", zona: "extra-europa" },
      { nume: "Uzbekistan", codISO: "UZ", cotaStandard: 15, sistem: "flat", zona: "extra-europa" },
      { nume: "Kârgâzstan", codISO: "KG", cotaStandard: 10, sistem: "flat", zona: "extra-europa" },
      { nume: "Tadjikistan", codISO: "TJ", cotaStandard: 18, sistem: "flat", zona: "extra-europa" },
      { nume: "Mongolia", codISO: "MN", cotaStandard: 25, sistem: "flat", zona: "extra-europa" },
      { nume: "Arabia Saudită", codISO: "SA", cotaStandard: 20, sistem: "flat", zona: "extra-europa" },
      { nume: "Emiratele Arabe Unite", codISO: "AE", cotaStandard: 9, sistem: "flat", detalii: "Introdus în 2023", zona: "extra-europa" },
      { nume: "Qatar", codISO: "QA", cotaStandard: 10, sistem: "flat", zona: "extra-europa" },
      { nume: "Kuwait", codISO: "KW", cotaStandard: 15, sistem: "flat", zona: "extra-europa" },
      { nume: "Bahrain", codISO: "BH", cotaStandard: 0, sistem: "flat", detalii: "Fără impozit pe profit (excepție petrol)", zona: "extra-europa" },
      { nume: "Oman", codISO: "OM", cotaStandard: 15, sistem: "flat", zona: "extra-europa" },
      { nume: "Israel", codISO: "IL", cotaStandard: 23, sistem: "flat", zona: "extra-europa" },
      { nume: "Iordania", codISO: "JO", cotaStandard: 20, sistem: "flat", zona: "extra-europa" },
      { nume: "Liban", codISO: "LB", cotaStandard: 17, sistem: "flat", zona: "extra-europa" },
      { nume: "Irak", codISO: "IQ", cotaStandard: 15, sistem: "flat", zona: "extra-europa" },
      { nume: "Iran", codISO: "IR", cotaStandard: 25, sistem: "flat", zona: "extra-europa" },
      { nume: "Egipt", codISO: "EG", cotaStandard: 22.5, sistem: "flat", zona: "extra-europa" },
      { nume: "Maroc", codISO: "MA", cotaStandard: 31, sistem: "flat", detalii: "20%–35% progresiv", zona: "extra-europa" },
      { nume: "Algeria", codISO: "DZ", cotaStandard: 26, sistem: "flat", zona: "extra-europa" },
      { nume: "Tunisia", codISO: "TN", cotaStandard: 15, sistem: "flat", zona: "extra-europa" },
      { nume: "Africa de Sud", codISO: "ZA", cotaStandard: 27, sistem: "flat", zona: "extra-europa" },
      { nume: "Nigeria", codISO: "NG", cotaStandard: 30, sistem: "flat", zona: "extra-europa" },
      { nume: "Kenya", codISO: "KE", cotaStandard: 30, sistem: "flat", zona: "extra-europa" },
      { nume: "Etiopia", codISO: "ET", cotaStandard: 30, sistem: "flat", zona: "extra-europa" },
      { nume: "Ghana", codISO: "GH", cotaStandard: 25, sistem: "flat", zona: "extra-europa" },
      { nume: "Tanzania", codISO: "TZ", cotaStandard: 30, sistem: "flat", zona: "extra-europa" },
      { nume: "Uganda", codISO: "UG", cotaStandard: 30, sistem: "flat", zona: "extra-europa" },
      { nume: "Australia", codISO: "AU", cotaStandard: 30, sistem: "flat", detalii: "25% pentru firme mici", zona: "extra-europa" },
      { nume: "Noua Zeelandă", codISO: "NZ", cotaStandard: 28, sistem: "flat", zona: "extra-europa" },
      { nume: "Fiji", codISO: "FJ", cotaStandard: 20, sistem: "flat", zona: "extra-europa" },
      { nume: "Papua Noua Guinee", codISO: "PG", cotaStandard: 30, sistem: "flat", zona: "extra-europa" },
    ],
    contextRomania:
      "România aplică o cotă de 16% pentru impozitul pe profit, în linie cu media europeană. Microîntreprinderile (sub 500.000 EUR cifră de afaceri) plătesc 1% pe cifra de afaceri brută, un avantaj semnificativ față de statele din vestul Europei. Din 2024, microîntreprinderile cu angajați plătesc 1%, cele fără angajați — 3%.",
    mediuEuropean: 20,
    istorie:
      "Impozitul pe profit modern a apărut la începutul secolului XX. Germania a introdus impozitul pe corporații în 1920. România a introdus impozitul pe profit în 1990, odată cu tranziția la economia de piață. Cota a variat între 38% (1991) și 16% (din 2005, odată cu introducerea cotei unice). Tendința globală a ultimilor 30 de ani este de scădere continuă a cotelor corporative — media globală a scăzut de la ~45% în 1985 la ~23% astăzi. Motivul: competiția fiscală între state pentru atragerea investițiilor străine. Irlanda este cel mai cunoscut exemplu: cota de 12.5% a atras sedii europene ale Google, Apple, Facebook și alte mari corporații tech.",
    fapteInteresante: [
      "Ungaria și Muntenegru au cele mai mici cote din Europa: 9% — avantaj competitiv major pentru companii.",
      "Irlanda (12.5%) găzduiește sediile europene ale celor mai mari corporații tech americane, generând venituri fiscale enorme.",
      "Estonia și Letonia nu impozitează profitul reinvestit — impozitul se plătește doar la distribuirea dividendelor, stimulând reinvestiția.",
      "Georgia (15%) permite scutire totală pe profitul reinvestit, devenind un centru de afaceri atractiv în Caucaz.",
      "Malta are formal cea mai mare cotă (35%), dar printr-un sistem de restituiri, companiile străine plătesc efectiv ~5%.",
    ],
  },

  "contributii-sociale": {
    id: "contributii-sociale",
    titlu: "Contribuții Sociale — Angajat + Angajator",
    descriere:
      "Comparație a totalului contribuțiilor sociale (angajat + angajator) în Europa. România: CAS 25% + CASS 10% (angajat).",
    unitateMasura: "%",
    culoare: "rgba(217, 119, 6, 0.85)",
    culoareSecundara: "rgba(217, 119, 6, 0.18)",
    emoji: "🤝",
    tari: [
      { nume: "Franța", codISO: "FR", cotaStandard: 68, sistem: "proporțional", detalii: "~42% angajator + 26% angajat" },
      { nume: "Slovacia", codISO: "SK", cotaStandard: 48.6, sistem: "proporțional", detalii: "35.2% angajator + 13.4% angajat" },
      { nume: "Cehia", codISO: "CZ", cotaStandard: 45, sistem: "proporțional", detalii: "33.8% angajator + 11.2% angajat" },
      { nume: "Italia", codISO: "IT", cotaStandard: 43, sistem: "proporțional", detalii: "~30% angajator + 13% angajat" },
      { nume: "Slovenia", codISO: "SI", cotaStandard: 38.2, sistem: "proporțional", detalii: "~16.1% angajator + 22.1% angajat" },
      { nume: "Finlanda", codISO: "FI", cotaStandard: 38.3, sistem: "proporțional", detalii: "~25% angajator + 13.3% angajat" },
      { nume: "Suedia", codISO: "SE", cotaStandard: 38.4, sistem: "proporțional", detalii: "~31.4% angajator + 7% angajat" },
      { nume: "Grecia", codISO: "GR", cotaStandard: 38.5, sistem: "proporțional", detalii: "~22% angajator + 16% angajat" },
      { nume: "Austria", codISO: "AT", cotaStandard: 39.9, sistem: "proporțional", detalii: "~21.7% angajator + 18.2% angajat" },
      { nume: "Belgia", codISO: "BE", cotaStandard: 40, sistem: "proporțional", detalii: "~27% angajator + 13.07% angajat" },
      { nume: "Germania", codISO: "DE", cotaStandard: 40, sistem: "proporțional", detalii: "~20% angajator + 20% angajat" },
      { nume: "Lituania", codISO: "LT", cotaStandard: 40.7, sistem: "proporțional", detalii: "~1.77% angajator + 19.5% angajat" },
      { nume: "Croația", codISO: "HR", cotaStandard: 36.5, sistem: "proporțional", detalii: "~16.5% angajator + 20% angajat" },
      { nume: "Spania", codISO: "ES", cotaStandard: 36.9, sistem: "proporțional", detalii: "~29.9% angajator + 6.4% angajat" },
      { nume: "Olanda", codISO: "NL", cotaStandard: 35.7, sistem: "proporțional", detalii: "~21.6% angajator + 13.1% angajat" },
      { nume: "Ungaria", codISO: "HU", cotaStandard: 33.5, sistem: "proporțional", detalii: "~15.5% angajator + 18% angajat" },
      { nume: "Estonia", codISO: "EE", cotaStandard: 33, sistem: "proporțional", detalii: "~33% angajator, 0% angajat" },
      { nume: "Bulgaria", codISO: "BG", cotaStandard: 32.7, sistem: "proporțional", detalii: "~18.9% angajator + 13.8% angajat" },
      { nume: "Letonia", codISO: "LV", cotaStandard: 34.09, sistem: "proporțional", detalii: "~23.59% angajator + 10.5% angajat" },
      { nume: "Portugalia", codISO: "PT", cotaStandard: 34.75, sistem: "proporțional", detalii: "~23.75% angajator + 11% angajat" },
      { nume: "Polonia", codISO: "PL", cotaStandard: 34.7, sistem: "proporțional", detalii: "~20.6% angajator + 13.7% angajat" },
      { nume: "Serbia", codISO: "RS", cotaStandard: 35, sistem: "proporțional", detalii: "~17.9% angajator + 17.1% angajat" },
      {
        nume: "România",
        codISO: "RO",
        cotaStandard: 35,
        sistem: "proporțional",
        detalii: "CAS 25% + CASS 10% (angajat); 2.25% CAM (angajator)",
        esteRomania: true,
      },
      { nume: "Norvegia", codISO: "NO", cotaStandard: 22.1, sistem: "proporțional", detalii: "~14.1% angajator + 7.9% angajat" },
      { nume: "Luxemburg", codISO: "LU", cotaStandard: 28.4, sistem: "proporțional", detalii: "~15.6% angajator + 12.8% angajat" },
      { nume: "Elveția", codISO: "CH", cotaStandard: 25.15, sistem: "proporțional", detalii: "~12.7% angajator + 12.45% angajat" },
      { nume: "UK", codISO: "GB", cotaStandard: 25.8, sistem: "proporțional", detalii: "~13.8% angajator + 12% angajat" },
      { nume: "Islanda", codISO: "IS", cotaStandard: 14.8, sistem: "proporțional", detalii: "~6.35% angajator + 4% angajat + fond pensie" },
      { nume: "Muntenegru", codISO: "ME", cotaStandard: 33.8, sistem: "proporțional", detalii: "~9.8% angajator + 24% angajat" },
      { nume: "Macedonia de Nord", codISO: "MK", cotaStandard: 27, sistem: "proporțional", detalii: "~7.5% angajator + 18% angajat" },
      { nume: "Albania", codISO: "AL", cotaStandard: 28, sistem: "proporțional", detalii: "~16% angajator + 11.2% angajat" },
      { nume: "Bosnia-Herțegovina", codISO: "BA", cotaStandard: 41.5, sistem: "proporțional", detalii: "FBiH: ~10.5% angajator + 31% angajat" },
      { nume: "Kosovo", codISO: "XK", cotaStandard: 10, sistem: "proporțional", detalii: "5% angajator + 5% angajat (pensie)" },
      { nume: "Moldova", codISO: "MD", cotaStandard: 24, sistem: "proporțional", detalii: "~18% angajator + 6% angajat" },
      { nume: "Ucraina", codISO: "UA", cotaStandard: 22, sistem: "proporțional", detalii: "~22% angajator, 0% angajat" },
      { nume: "Georgia", codISO: "GE", cotaStandard: 2, sistem: "proporțional", detalii: "2% angajat (pensie privată)" },
      { nume: "Azerbaijan", codISO: "AZ", cotaStandard: 25, sistem: "proporțional", detalii: "~22% angajator + 3% angajat" },
      { nume: "Armenia", codISO: "AM", cotaStandard: 17.5, sistem: "proporțional", detalii: "5% angajator + 2.5% angajat + pensie" },
      { nume: "Belarus", codISO: "BY", cotaStandard: 35.1, sistem: "proporțional", detalii: "~28% angajator + 1% angajat" },
      { nume: "Turcia", codISO: "TR", cotaStandard: 37.5, sistem: "proporțional", detalii: "~22.5% angajator + 15% angajat" },
      { nume: "Irlanda", codISO: "IE", cotaStandard: 15.15, sistem: "proporțional", detalii: "~11.15% angajator + 4% angajat" },
      { nume: "Danemarca", codISO: "DK", cotaStandard: 8, sistem: "proporțional", detalii: "~0% angajator + 8% angajat ATP" },
      // --- EXTRA-EUROPA ---
      { nume: "Statele Unite", codISO: "US", cotaStandard: 15.3, sistem: "proporțional", detalii: "7.65% angajat + 7.65% angajator (FICA)", zona: "extra-europa" },
      { nume: "Canada", codISO: "CA", cotaStandard: 11.9, sistem: "proporțional", detalii: "~5.95% angajat + 5.95% angajator (CPP+EI)", zona: "extra-europa" },
      { nume: "Mexic", codISO: "MX", cotaStandard: 22, sistem: "proporțional", detalii: "~8% angajat + 14% angajator", zona: "extra-europa" },
      { nume: "Brazilia", codISO: "BR", cotaStandard: 27, sistem: "proporțional", detalii: "~8% angajat + 19% angajator", zona: "extra-europa" },
      { nume: "Argentina", codISO: "AR", cotaStandard: 31.5, sistem: "proporțional", detalii: "~17% angajat + 14.5% angajator", zona: "extra-europa" },
      { nume: "Chile", codISO: "CL", cotaStandard: 20, sistem: "proporțional", detalii: "~20% angajat (pensie privată + sănătate)", zona: "extra-europa" },
      { nume: "Columbia", codISO: "CO", cotaStandard: 29, sistem: "proporțional", detalii: "~8% angajat + 21% angajator", zona: "extra-europa" },
      { nume: "Peru", codISO: "PE", cotaStandard: 13, sistem: "proporțional", detalii: "13% pensie (angajat)", zona: "extra-europa" },
      { nume: "China", codISO: "CN", cotaStandard: 38.5, sistem: "proporțional", detalii: "~10.5% angajat + 28% angajator", zona: "extra-europa" },
      { nume: "Japonia", codISO: "JP", cotaStandard: 29.8, sistem: "proporțional", detalii: "~14.9% angajat + 14.9% angajator", zona: "extra-europa" },
      { nume: "Coreea de Sud", codISO: "KR", cotaStandard: 18.5, sistem: "proporțional", detalii: "~9.25% angajat + 9.25% angajator", zona: "extra-europa" },
      { nume: "Australia", codISO: "AU", cotaStandard: 11, sistem: "proporțional", detalii: "11% super angajator (SGC)", zona: "extra-europa" },
      { nume: "India", codISO: "IN", cotaStandard: 24, sistem: "proporțional", detalii: "12% angajat + 12% angajator (EPF+ESI)", zona: "extra-europa" },
      { nume: "Arabia Saudită", codISO: "SA", cotaStandard: 21, sistem: "proporțional", detalii: "10% angajat + 11% angajator", zona: "extra-europa" },
      { nume: "Israel", codISO: "IL", cotaStandard: 17.5, sistem: "proporțional", detalii: "~7% angajat + 10.5% angajator", zona: "extra-europa" },
      { nume: "Egipt", codISO: "EG", cotaStandard: 40, sistem: "proporțional", detalii: "~14% angajat + 26% angajator", zona: "extra-europa" },
      { nume: "Africa de Sud", codISO: "ZA", cotaStandard: 2, sistem: "proporțional", detalii: "UIF: 1% angajat + 1% angajator", zona: "extra-europa" },
      { nume: "Nigeria", codISO: "NG", cotaStandard: 18, sistem: "proporțional", detalii: "8% angajat + 10% angajator (pension)", zona: "extra-europa" },
      { nume: "Kazahstan", codISO: "KZ", cotaStandard: 13, sistem: "proporțional", detalii: "10% angajat pensie + 3% angajator", zona: "extra-europa" },
    ],
    contextRomania:
      "În România, contribuțiile sociale sunt suportate integral de angajat: CAS 25% (pensie) și CASS 10% (sănătate) din salariul brut. Angajatorul plătește doar 2.25% CAM (contribuția asiguratorie pentru muncă). Această structură, introdusă în 2018, transferă povara fiscală asupra salariatului, crescând transparența costurilor.",
    mediuEuropean: 36,
    istorie:
      "Contribuțiile sociale moderne au apărut în Germania lui Bismarck, în 1883, odată cu introducerea primei asigurări de sănătate obligatorii la nivel național. Sistemul a fost extins treptat pentru a include pensiile (1889) și asigurarea de șomaj (1927). România a adoptat sistemul de asigurări sociale obligatorii în 1912, sub regele Carol I. Reformele majore post-1990 au restructurat sistemul spre un model contributiv. Marea reformă din 2018 a transferat contribuțiile de la angajator la angajat — salariile brute au crescut compensator, dar rata efectivă a rămas similară.",
    fapteInteresante: [
      "Franța are cel mai mare nivel de contribuții sociale din Europa (~68% combinat), dar și cel mai generos sistem de protecție socială.",
      "Danemarca are contribuții sociale foarte mici (~8%), dar finanțează sănătatea și pensiile în principal din impozite pe venit ridicate.",
      "Georgia are contribuții sociale aproape inexistente (2%) — unul din cele mai mici niveluri din Europa.",
      "Kosovo aplică doar 5%+5% pentru pensie — modelul contribuțional cel mai simplu din continent.",
    ],
  },

  "dividende": {
    id: "dividende",
    titlu: "Impozit pe Dividende",
    descriere:
      "Comparație a cotelor de impozit pe dividende pentru persoane fizice în Europa. România aplică 8% din 2024.",
    unitateMasura: "%",
    culoare: "rgba(220, 38, 38, 0.85)",
    culoareSecundara: "rgba(220, 38, 38, 0.18)",
    emoji: "💰",
    tari: [
      { nume: "Elveția", codISO: "CH", cotaStandard: 35, sistem: "flat", detalii: "35% impozit la sursă, recuperabil" },
      { nume: "Danemarca", codISO: "DK", cotaStandard: 42, sistem: "progresiv", detalii: "27% sub 58.900 DKK, 42% peste" },
      { nume: "Irlanda", codISO: "IE", cotaStandard: 33, sistem: "flat", detalii: "DIRT 33%" },
      { nume: "Norvegia", codISO: "NO", cotaStandard: 37.84, sistem: "flat", detalii: "22% + suprataxă" },
      { nume: "Franța", codISO: "FR", cotaStandard: 30, sistem: "flat", detalii: "Prélèvement Forfaitaire Unique 30%" },
      { nume: "Belgia", codISO: "BE", cotaStandard: 30, sistem: "flat", detalii: "Cotă fixă 30%" },
      { nume: "Suedia", codISO: "SE", cotaStandard: 30, sistem: "flat", detalii: "Cotă fixă 30%" },
      { nume: "UK", codISO: "GB", cotaStandard: 33.75, sistem: "progresiv", detalii: "8.75% / 33.75% / 39.35%" },
      { nume: "Portugalia", codISO: "PT", cotaStandard: 28, sistem: "flat", detalii: "Cotă fixă 28%" },
      { nume: "Spania", codISO: "ES", cotaStandard: 28, sistem: "progresiv", detalii: "19% / 21% / 23% / 28% pe tranșe" },
      { nume: "Italia", codISO: "IT", cotaStandard: 26, sistem: "flat", detalii: "Cotă fixă 26%" },
      { nume: "Finlanda", codISO: "FI", cotaStandard: 25.5, sistem: "flat", detalii: "Efectiv 25.5% din valoarea impozabilă" },
      { nume: "Germania", codISO: "DE", cotaStandard: 25, sistem: "flat", detalii: "Abgeltungsteuer 25% + 5.5% solidaritate" },
      { nume: "Slovenia", codISO: "SI", cotaStandard: 25, sistem: "flat", detalii: "Cotă fixă 25%" },
      { nume: "Olanda", codISO: "NL", cotaStandard: 24.5, sistem: "flat", detalii: "Box 2: 24.5% / 33% pe tranșe" },
      { nume: "Austria", codISO: "AT", cotaStandard: 27.5, sistem: "flat", detalii: "Cotă fixă 27.5%" },
      { nume: "Letonia", codISO: "LV", cotaStandard: 20, sistem: "flat", detalii: "Cotă fixă 20%" },
      { nume: "Estonia", codISO: "EE", cotaStandard: 20, sistem: "distributie", detalii: "20% la distribuire (0% reinvestit)" },
      { nume: "Islanda", codISO: "IS", cotaStandard: 22, sistem: "flat", detalii: "Cotă fixă 22%" },
      { nume: "Serbia", codISO: "RS", cotaStandard: 15, sistem: "flat", detalii: "Cotă fixă 15%" },
      { nume: "Albania", codISO: "AL", cotaStandard: 8, sistem: "flat", detalii: "Cotă fixă 8%" },
      { nume: "Macedonia de Nord", codISO: "MK", cotaStandard: 10, sistem: "flat", detalii: "Cotă fixă 10%" },
      { nume: "Muntenegru", codISO: "ME", cotaStandard: 9, sistem: "flat", detalii: "Cotă fixă 9%" },
      { nume: "Kosovo", codISO: "XK", cotaStandard: 10, sistem: "flat", detalii: "Cotă fixă 10%" },
      { nume: "Bosnia-Herțegovina", codISO: "BA", cotaStandard: 10, sistem: "flat", detalii: "Cotă fixă 10%" },
      { nume: "Moldova", codISO: "MD", cotaStandard: 6, sistem: "flat", detalii: "Cotă fixă 6%" },
      { nume: "Ucraina", codISO: "UA", cotaStandard: 5, sistem: "flat", detalii: "5% (9% pentru nerezidenti)" },
      { nume: "Georgia", codISO: "GE", cotaStandard: 5, sistem: "flat", detalii: "Cotă fixă 5%" },
      { nume: "Azerbaijan", codISO: "AZ", cotaStandard: 14, sistem: "flat", detalii: "Cotă fixă 14%" },
      { nume: "Armenia", codISO: "AM", cotaStandard: 5, sistem: "flat", detalii: "Cotă fixă 5%" },
      { nume: "Belarus", codISO: "BY", cotaStandard: 13, sistem: "flat", detalii: "Cotă fixă 13%" },
      { nume: "Turcia", codISO: "TR", cotaStandard: 15, sistem: "flat", detalii: "Cotă fixă 15% reținut la sursă" },
      { nume: "Andorra", codISO: "AD", cotaStandard: 10, sistem: "flat", detalii: "Cotă fixă 10%" },
      { nume: "Liechtenstein", codISO: "LI", cotaStandard: 12.5, sistem: "flat", detalii: "12.5% reținut la sursă" },
      { nume: "San Marino", codISO: "SM", cotaStandard: 5, sistem: "flat", detalii: "Cotă fixă 5%" },
      { nume: "Polonia", codISO: "PL", cotaStandard: 19, sistem: "flat", detalii: "Cotă fixă 19%" },
      { nume: "Cehia", codISO: "CZ", cotaStandard: 15, sistem: "flat", detalii: "Cotă fixă 15%" },
      { nume: "Slovacia", codISO: "SK", cotaStandard: 7, sistem: "flat", detalii: "7% pentru dividende din 2024" },
      { nume: "Ungaria", codISO: "HU", cotaStandard: 15, sistem: "flat", detalii: "Cotă fixă 15%" },
      { nume: "Croația", codISO: "HR", cotaStandard: 10, sistem: "flat", detalii: "Cotă fixă 10%" },
      { nume: "Lituania", codISO: "LT", cotaStandard: 15, sistem: "flat", detalii: "Cotă fixă 15%" },
      { nume: "Luxemburg", codISO: "LU", cotaStandard: 15, sistem: "flat", detalii: "Cotă minimă 15%" },
      {
        nume: "România",
        codISO: "RO",
        cotaStandard: 8,
        sistem: "flat",
        detalii: "Cotă fixă 8% din 2024 (anterior 5%)",
        esteRomania: true,
      },
      { nume: "Bulgaria", codISO: "BG", cotaStandard: 5, sistem: "flat", detalii: "Cea mai mică din UE" },
      { nume: "Cipru", codISO: "CY", cotaStandard: 0, sistem: "flat", detalii: "0% — scutite complet" },
      { nume: "Malta", codISO: "MT", cotaStandard: 15, sistem: "flat", detalii: "Rambursare parțială posibilă" },
      { nume: "Monaco", codISO: "MC", cotaStandard: 0, sistem: "flat", detalii: "0% — fără impozit pe dividende" },
      // --- EXTRA-EUROPA ---
      { nume: "Statele Unite", codISO: "US", cotaStandard: 20, sistem: "progresiv", detalii: "0%/15%/20% Qualified Dividends", zona: "extra-europa" },
      { nume: "Canada", codISO: "CA", cotaStandard: 29, sistem: "flat", detalii: "~29% efectiv (gross-up + credit)", zona: "extra-europa" },
      { nume: "Mexic", codISO: "MX", cotaStandard: 10, sistem: "flat", zona: "extra-europa" },
      { nume: "Brazilia", codISO: "BR", cotaStandard: 0, sistem: "flat", detalii: "Scutite din 2022 (propunere reimpozitare în dezbatere)", zona: "extra-europa" },
      { nume: "Argentina", codISO: "AR", cotaStandard: 7, sistem: "flat", zona: "extra-europa" },
      { nume: "Chile", codISO: "CL", cotaStandard: 35, sistem: "progresiv", detalii: "Cotă marginală 35%", zona: "extra-europa" },
      { nume: "Columbia", codISO: "CO", cotaStandard: 20, sistem: "flat", zona: "extra-europa" },
      { nume: "Peru", codISO: "PE", cotaStandard: 5, sistem: "flat", zona: "extra-europa" },
      { nume: "China", codISO: "CN", cotaStandard: 20, sistem: "flat", zona: "extra-europa" },
      { nume: "Japonia", codISO: "JP", cotaStandard: 20.315, sistem: "flat", detalii: "15.315% + 5% local", zona: "extra-europa" },
      { nume: "Coreea de Sud", codISO: "KR", cotaStandard: 15.4, sistem: "flat", detalii: "14% + 1.4% local", zona: "extra-europa" },
      { nume: "Taiwan", codISO: "TW", cotaStandard: 28, sistem: "flat", detalii: "Inclus în venitul global sau 28% separat", zona: "extra-europa" },
      { nume: "Hong Kong", codISO: "HK", cotaStandard: 0, sistem: "flat", detalii: "Fără impozit pe dividende", zona: "extra-europa" },
      { nume: "Singapore", codISO: "SG", cotaStandard: 0, sistem: "flat", detalii: "Scutite complet", zona: "extra-europa" },
      { nume: "Malaysia", codISO: "MY", cotaStandard: 0, sistem: "flat", detalii: "Sistem single-tier: scutite", zona: "extra-europa" },
      { nume: "Thailanda", codISO: "TH", cotaStandard: 10, sistem: "flat", zona: "extra-europa" },
      { nume: "Vietnam", codISO: "VN", cotaStandard: 5, sistem: "flat", zona: "extra-europa" },
      { nume: "Filipine", codISO: "PH", cotaStandard: 10, sistem: "flat", zona: "extra-europa" },
      { nume: "Indonesia", codISO: "ID", cotaStandard: 10, sistem: "flat", zona: "extra-europa" },
      { nume: "India", codISO: "IN", cotaStandard: 20, sistem: "flat", detalii: "TDS 20% pentru nerezidenti", zona: "extra-europa" },
      { nume: "Pakistan", codISO: "PK", cotaStandard: 15, sistem: "flat", zona: "extra-europa" },
      { nume: "Kazahstan", codISO: "KZ", cotaStandard: 5, sistem: "flat", zona: "extra-europa" },
      { nume: "Arabia Saudită", codISO: "SA", cotaStandard: 5, sistem: "flat", detalii: "WHT 5% pentru nerezidenti", zona: "extra-europa" },
      { nume: "Emiratele Arabe Unite", codISO: "AE", cotaStandard: 0, sistem: "flat", detalii: "Fără impozit pe dividende", zona: "extra-europa" },
      { nume: "Israel", codISO: "IL", cotaStandard: 25, sistem: "flat", detalii: "25% sau 30% pentru acționar majoritar", zona: "extra-europa" },
      { nume: "Egipt", codISO: "EG", cotaStandard: 10, sistem: "flat", zona: "extra-europa" },
      { nume: "Africa de Sud", codISO: "ZA", cotaStandard: 20, sistem: "flat", detalii: "Dividends Tax 20%", zona: "extra-europa" },
      { nume: "Australia", codISO: "AU", cotaStandard: 30, sistem: "flat", detalii: "WHT 30% (15% cu tratat fiscal)", zona: "extra-europa" },
      { nume: "Noua Zeelandă", codISO: "NZ", cotaStandard: 33, sistem: "flat", detalii: "RWT maxim 33%", zona: "extra-europa" },
    ],
    contextRomania:
      "România a majorat cota de impozit pe dividende de la 5% la 8% în 2024. Rămâne sub media europeană, competitivă față de Germania (25%) sau Franța (30%). Dividendele se declară prin D205 (anual) și D212 dacă destinatarul e persoană fizică cu alte venituri. Impozitul se reține la sursă de societate la momentul distribuirii.",
    mediuEuropean: 22,
    istorie:
      "Impozitarea dividendelor a apărut din nevoia de a taxa distribuirea profitului corporativ la persoane fizice. Istoric, dividendele erau impozitate de două ori: odată ca profit al firmei, o dată ca venit al acționarului. Multe țări au introdus cote reduse sau scutiri pentru a evita dubla impozitare. România a introdus impozitul pe dividende în 2005 cu 10%, l-a redus la 5% în 2017 și l-a majorat la 8% în 2024 în contextul nevoilor de venituri bugetare.",
    fapteInteresante: [
      "Cipru și Monaco scutesc complet dividendele — factori majori în atragerea companiilor holding și milionarilor.",
      "Estonia nu impozitează profitul reinvestit, ci doar cel distribuit (20%), stimulând capitalizarea companiilor.",
      "Elveția aplică 35% la sursă, dar sumele sunt recuperabile prin declarație dacă există convenție fiscală cu țara de rezidență.",
      "Bulgaria și România au cele mai mici cote de dividende din UE — 5% și respectiv 8%.",
      "Georgia și Ucraina aplică doar 5% — atrăgând investitori din regiune.",
    ],
  },

  "prag-tva": {
    id: "prag-tva",
    titlu: "Prag Înregistrare TVA",
    descriere:
      "Comparație a pragurilor de înregistrare obligatorie în scopuri de TVA în Europa. România: 300.000 lei (~60.000 EUR).",
    unitateMasura: "k EUR",
    culoare: "rgba(5, 150, 105, 0.85)",
    culoareSecundara: "rgba(5, 150, 105, 0.18)",
    emoji: "📋",
    tari: [
      { nume: "UK", codISO: "GB", cotaStandard: 113, sistem: "flat", detalii: "£90.000 (apr. 113k EUR)" },
      { nume: "Italia", codISO: "IT", cotaStandard: 85, sistem: "flat", detalii: "Regim forfetare sub 85k EUR" },
      { nume: "Franța", codISO: "FR", cotaStandard: 85, sistem: "flat", detalii: "Micro-entreprise sub 85k EUR" },
      { nume: "Cehia", codISO: "CZ", cotaStandard: 84, sistem: "flat", detalii: "2M CZK (~84k EUR)" },
      { nume: "Irlanda", codISO: "IE", cotaStandard: 80, sistem: "flat", detalii: "80.000 EUR (servicii) / 37.500 EUR (bunuri)" },
      { nume: "Suedia", codISO: "SE", cotaStandard: 80, sistem: "flat", detalii: "800.000 SEK (~80k EUR)" },
      { nume: "România", codISO: "RO", cotaStandard: 60, sistem: "flat", detalii: "300.000 lei (~60.000 EUR)", esteRomania: true },
      { nume: "Slovenia", codISO: "SI", cotaStandard: 50, sistem: "flat", detalii: "50.000 EUR" },
      { nume: "Norvegia", codISO: "NO", cotaStandard: 50, sistem: "flat", detalii: "50.000 NOK (~4.5k EUR)" },
      { nume: "Polonia", codISO: "PL", cotaStandard: 47, sistem: "flat", detalii: "200.000 PLN (~47k EUR)" },
      { nume: "Lituania", codISO: "LT", cotaStandard: 45, sistem: "flat", detalii: "45.000 EUR" },
      { nume: "Estonia", codISO: "EE", cotaStandard: 40, sistem: "flat", detalii: "40.000 EUR" },
      { nume: "Letonia", codISO: "LV", cotaStandard: 40, sistem: "flat", detalii: "40.000 EUR" },
      { nume: "Croația", codISO: "HR", cotaStandard: 40, sistem: "flat", detalii: "40.000 EUR" },
      { nume: "Serbia", codISO: "RS", cotaStandard: 38, sistem: "flat", detalii: "8M RSD (~68k EUR)" },
      { nume: "Austria", codISO: "AT", cotaStandard: 35, sistem: "flat", detalii: "35.000 EUR" },
      { nume: "Islanda", codISO: "IS", cotaStandard: 28, sistem: "flat", detalii: "2M ISK (~14k EUR)" },
      { nume: "Bulgaria", codISO: "BG", cotaStandard: 25.6, sistem: "flat", detalii: "50.000 BGN (~25.6k EUR)" },
      { nume: "Belgia", codISO: "BE", cotaStandard: 25, sistem: "flat", detalii: "25.000 EUR" },
      { nume: "Olanda", codISO: "NL", cotaStandard: 20, sistem: "flat", detalii: "Scutire mici afaceri sub 20k EUR" },
      { nume: "Germania", codISO: "DE", cotaStandard: 22, sistem: "flat", detalii: "Kleinunternehmer sub 22k EUR opt-out" },
      { nume: "Ungaria", codISO: "HU", cotaStandard: 24, sistem: "flat", detalii: "12M HUF (~24k EUR)" },
      { nume: "Muntenegru", codISO: "ME", cotaStandard: 30, sistem: "flat", detalii: "30.000 EUR" },
      { nume: "Macedonia de Nord", codISO: "MK", cotaStandard: 25, sistem: "flat", detalii: "1M MKD (~16k EUR)" },
      { nume: "Albania", codISO: "AL", cotaStandard: 10, sistem: "flat", detalii: "10M ALL (~10k EUR)" },
      { nume: "Kosovo", codISO: "XK", cotaStandard: 30, sistem: "flat", detalii: "30.000 EUR" },
      { nume: "Bosnia-Herțegovina", codISO: "BA", cotaStandard: 50, sistem: "flat", detalii: "50.000 BAM (~25.5k EUR)" },
      { nume: "Moldova", codISO: "MD", cotaStandard: 21, sistem: "flat", detalii: "1.2M MDL (~63k EUR)" },
      { nume: "Ucraina", codISO: "UA", cotaStandard: 30, sistem: "flat", detalii: "1M UAH (~23k EUR)" },
      { nume: "Georgia", codISO: "GE", cotaStandard: 28, sistem: "flat", detalii: "100.000 GEL (~28k EUR)" },
      { nume: "Azerbaijan", codISO: "AZ", cotaStandard: 25, sistem: "flat", detalii: "200.000 AZN (~25k EUR)" },
      { nume: "Armenia", codISO: "AM", cotaStandard: 21, sistem: "flat", detalii: "115M AMD (~21k EUR)" },
      { nume: "Belarus", codISO: "BY", cotaStandard: 0, sistem: "flat", detalii: "Fără prag — toți plătitorii de TVA" },
      { nume: "Turcia", codISO: "TR", cotaStandard: 0, sistem: "flat", detalii: "Fără prag minim formal" },
      { nume: "Spania", codISO: "ES", cotaStandard: 0, sistem: "flat", detalii: "Fără prag — obligatoriu de la prima tranzacție" },
      { nume: "Finlanda", codISO: "FI", cotaStandard: 15, sistem: "flat", detalii: "15.000 EUR" },
      { nume: "Cipru", codISO: "CY", cotaStandard: 15.6, sistem: "flat", detalii: "15.600 EUR" },
      { nume: "Luxeburg", codISO: "LU", cotaStandard: 35, sistem: "flat", detalii: "35.000 EUR" },
      { nume: "Slovacia", codISO: "SK", cotaStandard: 49.8, sistem: "flat", detalii: "49.790 EUR" },
      { nume: "Grecia", codISO: "GR", cotaStandard: 10, sistem: "flat", detalii: "10.000 EUR" },
      { nume: "Portugalia", codISO: "PT", cotaStandard: 13, sistem: "flat", detalii: "13.500 EUR (servicii) / 15.000 EUR (comerț)" },
      { nume: "Danemarca", codISO: "DK", cotaStandard: 8, sistem: "flat", detalii: "50.000 DKK (~6.7k EUR)" },
      { nume: "Liechtenstein", codISO: "LI", cotaStandard: 100, sistem: "flat", detalii: "100.000 CHF (~100k EUR)" },
      { nume: "Elveția", codISO: "CH", cotaStandard: 100, sistem: "flat", detalii: "100.000 CHF (~100k EUR)" },
      // --- EXTRA-EUROPA ---
      { nume: "Australia", codISO: "AU", cotaStandard: 59, sistem: "flat", detalii: "AUD 75.000 (~49k EUR)", zona: "extra-europa" },
      { nume: "Noua Zeelandă", codISO: "NZ", cotaStandard: 57, sistem: "flat", detalii: "NZD 60.000 (~34k EUR)", zona: "extra-europa" },
      { nume: "Canada", codISO: "CA", cotaStandard: 25, sistem: "flat", detalii: "CAD 30.000 (~21k EUR)", zona: "extra-europa" },
      { nume: "Statele Unite", codISO: "US", cotaStandard: 0, sistem: "flat", detalii: "Fără TVA federal", zona: "extra-europa" },
      { nume: "Mexic", codISO: "MX", cotaStandard: 0, sistem: "flat", detalii: "Fără prag — obligatoriu", zona: "extra-europa" },
      { nume: "Arabia Saudită", codISO: "SA", cotaStandard: 0, sistem: "flat", detalii: "Fără prag formal", zona: "extra-europa" },
      { nume: "Singapore", codISO: "SG", cotaStandard: 1000, sistem: "flat", detalii: "SGD 1 milion (~700k EUR) — cel mai mare din lume", zona: "extra-europa" },
      { nume: "India", codISO: "IN", cotaStandard: 20, sistem: "flat", detalii: "INR 2.000.000 (~22k EUR)", zona: "extra-europa" },
      { nume: "Japonia", codISO: "JP", cotaStandard: 100, sistem: "flat", detalii: "JPY 10 milioane (~60k EUR)", zona: "extra-europa" },
      { nume: "China", codISO: "CN", cotaStandard: 5, sistem: "flat", detalii: "CNY 50.000/lună (~5k EUR)", zona: "extra-europa" },
      { nume: "Africa de Sud", codISO: "ZA", cotaStandard: 80, sistem: "flat", detalii: "ZAR 1 milion (~50k EUR)", zona: "extra-europa" },
      { nume: "Brazilia", codISO: "BR", cotaStandard: 0, sistem: "flat", detalii: "Fără prag — toți se înregistrează", zona: "extra-europa" },
      { nume: "Israel", codISO: "IL", cotaStandard: 100, sistem: "flat", detalii: "ILS 120.000 (~30k EUR)", zona: "extra-europa" },
    ],
    contextRomania:
      "România impune înregistrarea TVA obligatorie la depășirea plafonului de 300.000 lei (~60.000 EUR) anual. Aceasta este una din cele mai generoase praguri din UE. Contribuabilii sub prag pot opta voluntar pentru plata TVA. Depășirea plafonului obligă la înregistrare în termen de 10 zile de la sfârșitul lunii în care a fost depășit.",
    mediuEuropean: 45,
    istorie:
      "Pragurile de TVA au apărut pentru a reduce povara administrativă asupra micilor afaceri. UE permite statelor membre să mențină praguri naționale, cu maximum 85.000 EUR din 2025 (conform Directivei UE 2020/285). Înainte de 2025, limita UE era de 35.000 EUR, dar România a menținut un prag mai mare prin excepție. Tendința în UE este de armonizare și creștere a pragului permis.",
    fapteInteresante: [
      "Elveția și Liechtenstein au cel mai mare prag din Europa: 100.000 CHF (~100k EUR), protejând maximum micii antreprenori.",
      "Spania nu are prag — orice activitate economică, indiferent de cifra de afaceri, este obligatorie la TVA de la prima tranzacție.",
      "UK, post-Brexit, a crescut pragul la £90.000 (cel mai mare din Europa continentală), oferind mai multă flexibilitate micilor afaceri.",
      "România are unul din cele mai generoase praguri din UE (~60k EUR), protejând micii antreprenori de birocrația TVA.",
      "Danemarca are cel mai mic prag din UE (~6.7k EUR) — aproape orice activitate comercială devine plătitoare de TVA.",
    ],
  },

  "impozit-avere": {
    id: "impozit-avere",
    titlu: "Impozit pe Avere / Proprietăți",
    descriere:
      "Comparație a sistemelor de impozitare a averii și proprietăților imobiliare în Europa.",
    unitateMasura: "%",
    culoare: "rgba(124, 58, 237, 0.85)",
    culoareSecundara: "rgba(124, 58, 237, 0.18)",
    emoji: "🏠",
    tari: [
      { nume: "Spania", codISO: "ES", cotaStandard: 2.5, sistem: "progresiv", detalii: "IP: 0.2%–2.5% din avere netă (regional)" },
      { nume: "Norvegia", codISO: "NO", cotaStandard: 1.1, sistem: "flat", detalii: "Formuesskatt: 1.1% din avere netă > 1.7M NOK" },
      { nume: "Letonia", codISO: "LV", cotaStandard: 1.5, sistem: "progresiv", detalii: "Nekustamā īpašuma nodoklis 0.2%–1.5%" },
      { nume: "Franța", codISO: "FR", cotaStandard: 1.5, sistem: "progresiv", detalii: "IFI: 0.5%–1.5% pe proprietăți imobiliare > 1.3M EUR" },
      { nume: "Portugalia", codISO: "PT", cotaStandard: 1.5, sistem: "progresiv", detalii: "IMI + AIMI 0.4%–1.5% din valoarea fiscală" },
      { nume: "UK", codISO: "GB", cotaStandard: 1.2, sistem: "progresiv", detalii: "Council Tax variabil, plus Stamp Duty la cumpărare" },
      { nume: "Olanda", codISO: "NL", cotaStandard: 1.2, sistem: "flat", detalii: "Box 3: 1.2% din avere netă (ficțional)" },
      { nume: "Lituania", codISO: "LT", cotaStandard: 1.0, sistem: "progresiv", detalii: "Nekilnojamojo turto mokestis 0.5%–1%" },
      { nume: "Danemarca", codISO: "DK", cotaStandard: 1.0, sistem: "progresiv", detalii: "Ejendomsværdiskat 0.44%–1%" },
      { nume: "Serbia", codISO: "RS", cotaStandard: 0.4, sistem: "progresiv", detalii: "Porez na imovinu 0.1%–0.4%" },
      { nume: "Croația", codISO: "HR", cotaStandard: 0.6, sistem: "flat", detalii: "Porez na nekretnine local max 0.6%" },
      { nume: "Italia", codISO: "IT", cotaStandard: 0.76, sistem: "flat", detalii: "IMU: 0.5%–0.76% din valoarea cadastrală ajustată" },
      { nume: "Suedia", codISO: "SE", cotaStandard: 0.75, sistem: "flat", detalii: "Fastighetsskatt plafon anual ~0.75%" },
      { nume: "Elveția", codISO: "CH", cotaStandard: 0.5, sistem: "progresiv", detalii: "Vermögensteuer cantonal: 0.1%–0.8% avere" },
      { nume: "Finlanda", codISO: "FI", cotaStandard: 0.93, sistem: "flat", detalii: "Kiinteistövero local 0.41%–0.93%" },
      { nume: "Ungaria", codISO: "HU", cotaStandard: 0.3, sistem: "flat", detalii: "Épít­mény­adó local maxim 0.3% din valoare" },
      { nume: "Turcia", codISO: "TR", cotaStandard: 0.3, sistem: "progresiv", detalii: "Emlak Vergisi 0.1%–0.3%" },
      { nume: "Bulgaria", codISO: "BG", cotaStandard: 0.2, sistem: "flat", detalii: "0.15%–0.25% din valoarea de piață" },
      { nume: "Irlanda", codISO: "IE", cotaStandard: 0.18, sistem: "progresiv", detalii: "LPT: 0.1%–0.18% din valoarea estimată" },
      { nume: "Belarus", codISO: "BY", cotaStandard: 0.1, sistem: "flat", detalii: "0.1% din valoarea cadastrală" },
      { nume: "Belgia", codISO: "BE", cotaStandard: 0.15, sistem: "flat", detalii: "Taxă anuală locuință 0.1%–0.15% din valoare cadastrală" },
      { nume: "Slovenia", codISO: "SI", cotaStandard: 0.15, sistem: "flat", detalii: "Nadomestilo za uporabo stavbnega zemljišča" },
      { nume: "Cehia", codISO: "CZ", cotaStandard: 0.1, sistem: "flat", detalii: "Daň z nemovitých věcí: taxă mică per mp" },
      { nume: "Polonia", codISO: "PL", cotaStandard: 0.1, sistem: "flat", detalii: "Podatek od nieruchomości: taxă fixă per mp (micro)" },
      { nume: "Slovacia", codISO: "SK", cotaStandard: 0.1, sistem: "flat", detalii: "Daň z nehnuteľností local" },
      { nume: "Austria", codISO: "AT", cotaStandard: 0.1, sistem: "flat", detalii: "Grundsteuer bazat pe valoare cadastrală veche" },
      { nume: "Ucraina", codISO: "UA", cotaStandard: 0.1, sistem: "flat", detalii: "0.1% din valoarea de piață minimă" },
      { nume: "Moldova", codISO: "MD", cotaStandard: 0.1, sistem: "flat", detalii: "0.05%–0.4% din valoarea estimată" },
      { nume: "Macedonia de Nord", codISO: "MK", cotaStandard: 0.2, sistem: "flat", detalii: "0.1%–0.2% din valoarea de piață" },
      { nume: "Albania", codISO: "AL", cotaStandard: 0.15, sistem: "flat", detalii: "0.05%–0.2% din valoarea cadastrală" },
      { nume: "Kosovo", codISO: "XK", cotaStandard: 0.4, sistem: "flat", detalii: "0.15%–0.4% din valoarea cadastrală" },
      { nume: "Bosnia-Herțegovina", codISO: "BA", cotaStandard: 0.5, sistem: "flat", detalii: "Entitate-specific, ~0.1%–0.5%" },
      { nume: "Muntenegru", codISO: "ME", cotaStandard: 1.0, sistem: "progresiv", detalii: "0.25%–1% din valoarea de piață" },
      { nume: "Georgia", codISO: "GE", cotaStandard: 0, sistem: "flat", detalii: "Fără impozit pe avere personală" },
      { nume: "Azerbaijan", codISO: "AZ", cotaStandard: 0.1, sistem: "flat", detalii: "0.1% din valoarea cadastrală" },
      { nume: "Armenia", codISO: "AM", cotaStandard: 0.1, sistem: "flat", detalii: "Taxă pe proprietate locală mică" },
      { nume: "Islanda", codISO: "IS", cotaStandard: 1.5, sistem: "flat", detalii: "Eignarskattur 1.5% pe avere netă > 75M ISK" },
      { nume: "Germania", codISO: "DE", cotaStandard: 0, sistem: "flat", detalii: "Vermögensteuer abolit 1997 — taxă proprietăți mică (~0.02%)" },
      { nume: "Luxemburg", codISO: "LU", cotaStandard: 0.5, sistem: "flat", detalii: "Impôt foncier ~0.5% din valoarea cadastrală" },
      { nume: "Cipru", codISO: "CY", cotaStandard: 0, sistem: "flat", detalii: "Fără impozit pe avere sau proprietăți imobiliare" },
      { nume: "Malta", codISO: "MT", cotaStandard: 0, sistem: "flat", detalii: "Fără impozit anual pe proprietăți" },
      { nume: "Andorra", codISO: "AD", cotaStandard: 0, sistem: "flat", detalii: "Fără impozit pe avere sau proprietăți" },
      { nume: "Monaco", codISO: "MC", cotaStandard: 0, sistem: "flat", detalii: "Fără impozit pe avere sau proprietăți" },
      { nume: "Liechtenstein", codISO: "LI", cotaStandard: 0.1, sistem: "flat", detalii: "Vermögenssteuer local ~0.06%–0.3%" },
      {
        nume: "România",
        codISO: "RO",
        cotaStandard: 0.08,
        sistem: "progresiv",
        detalii: "Impozit local: 0.08%–0.2% din valoarea impozabilă (rezidențial)",
        esteRomania: true,
      },
      // --- EXTRA-EUROPA ---
      { nume: "Statele Unite", codISO: "US", cotaStandard: 0.5, sistem: "flat", detalii: "Property tax local: ~0.5%–2.5% din valoarea de piață", zona: "extra-europa" },
      { nume: "Canada", codISO: "CA", cotaStandard: 0.7, sistem: "flat", detalii: "Property tax local ~0.5%–1.5%", zona: "extra-europa" },
      { nume: "Australia", codISO: "AU", cotaStandard: 0.5, sistem: "flat", detalii: "Council rates ~0.3%–0.8%", zona: "extra-europa" },
      { nume: "India", codISO: "IN", cotaStandard: 0.5, sistem: "flat", detalii: "Property tax municipal ~0.1%–0.5%", zona: "extra-europa" },
      { nume: "China", codISO: "CN", cotaStandard: 0.5, sistem: "flat", detalii: "Taxă proprietate 0.4%–1.2%", zona: "extra-europa" },
      { nume: "Japonia", codISO: "JP", cotaStandard: 1.4, sistem: "flat", detalii: "Impozit pe proprietăți 1.4%", zona: "extra-europa" },
      { nume: "Columbia", codISO: "CO", cotaStandard: 1.5, sistem: "progresiv", detalii: "Impuesto al patrimonio 0.5%–1.5%", zona: "extra-europa" },
      { nume: "Argentina", codISO: "AR", cotaStandard: 0.75, sistem: "flat", detalii: "Bienes Personales 0.5%–0.75%", zona: "extra-europa" },
      { nume: "Uruguay", codISO: "UY", cotaStandard: 1.5, sistem: "progresiv", detalii: "IRPF + Impuesto al patrimonio max 1.5%", zona: "extra-europa" },
      { nume: "Brazilia", codISO: "BR", cotaStandard: 0.3, sistem: "flat", detalii: "IPTU local ~0.3%–1.5%", zona: "extra-europa" },
      { nume: "Africa de Sud", codISO: "ZA", cotaStandard: 0.5, sistem: "flat", detalii: "Rates and taxes municipal ~0.5%", zona: "extra-europa" },
      { nume: "Arabia Saudită", codISO: "SA", cotaStandard: 2.5, sistem: "flat", detalii: "Zakat 2.5% pe averea netă (pentru musulmani)", zona: "extra-europa" },
      { nume: "Singapore", codISO: "SG", cotaStandard: 0.4, sistem: "flat", detalii: "Property tax: 4% rezidențial / 10% nerezidențial", zona: "extra-europa" },
      { nume: "Hong Kong", codISO: "HK", cotaStandard: 0, sistem: "flat", detalii: "Fără impozit pe avere", zona: "extra-europa" },
      { nume: "Emiratele Arabe Unite", codISO: "AE", cotaStandard: 0, sistem: "flat", detalii: "Fără impozit pe proprietăți sau avere", zona: "extra-europa" },
      { nume: "Qatar", codISO: "QA", cotaStandard: 0, sistem: "flat", detalii: "Fără impozit pe avere", zona: "extra-europa" },
      { nume: "Kuwait", codISO: "KW", cotaStandard: 0, sistem: "flat", detalii: "Fără impozit pe avere", zona: "extra-europa" },
      { nume: "Bahrain", codISO: "BH", cotaStandard: 0, sistem: "flat", detalii: "Fără impozit pe avere", zona: "extra-europa" },
    ],
    contextRomania:
      "România aplică un impozit local pe clădiri rezidențiale de 0.08%–0.2% din valoarea impozabilă, stabilit de consiliile locale. Valoarea impozabilă se calculează pe baza suprafeței și a unor coeficienți de zonă, nu pe valoarea de piață reală — ceea ce menține sarcina fiscală foarte scăzută față de țările vest-europene. Clădirile nerezidențiale au o cotă mai mare: 0.2%–1.3%.",
    mediuEuropean: 0.6,
    istorie:
      "Impozitele pe avere au o lungă istorie în Europa, pornind de la taxele medievale pe pământ. Franța a introdus ISF (impôt sur la fortune) în 1982, transformat în IFI (limitat la imobile) în 2018 sub Macron. Germania a abolit impozitul pe avere în 1997 după ce Curtea Constituțională l-a declarat neconstituțional. Suedia l-a abolit în 2007. Tendința globală actuală, influențată de dezbateri privind inegalitatea, este de reintroducere a unor forme de impozit pe avere, în special în SUA și Franța.",
    fapteInteresante: [
      "Germania, Cipru, Malta, Monaco, Andorra și Georgia nu au impozit pe avere sau proprietăți — atrag capitaluri și rezidenți bogați.",
      "Franța a restrâns impozitul pe avere la imobile în 2018 (IFI), excludând acțiunile și activele financiare pentru a evita fuga capitalului.",
      "Norvegia taxează averea netă la 1.1% — una din puținele țări care menține un impozit real pe avere.",
      "România are unul din cele mai mici impozite pe proprietăți din Europa — calculul pe valori cadastrale vechi menține sarcina fiscală minimă.",
      "Islanda are un impozit pe avere netă de 1.5% peste un prag ridicat — printre cele mai înalte din Europa.",
    ],
  },
};

export const COMPARATII_IDS = Object.keys(COMPARATII);
